all: false
structname: Mock{{.InterfaceName}}
template: testify
filename: "{{.InterfaceName}}.go"
template-data:
  unroll-variadic: true
packages:
  go.lumeweb.com/portal-plugin-abuse/internal/pkg/email:
    config:
      dir: internal/pkg/email
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: email
    interfaces:
      ContentExtractor: {}
      IMAPClientConn: {}
      IMAPDialer: {}
      IMAPClient: {}
  go.lumeweb.com/portal-plugin-abuse/internal/pkg/scanner:
    config:
      dir: internal/pkg/scanner/mocks
      pkgname: mocks
    interfaces:
      CoreStorageProtocolComposite: {}
      ScannerClient: {}
  go.lumeweb.com/portal-plugin-abuse/internal/types/service:
    config:
      dir: internal/service/mocks
      pkgname: mocks
    interfaces:
      AbuseReportService: {}
      BlockListService: {}
      CaseService: {}
      CommunicationService: {}
      EmailService: {}
      EvidenceService: {}
      ReporterService: {}
      ScanService: {}
      SearchService: {}
      SubjectService: {}
      TokenService: {}