// Code generated by mockery. DO NOT EDIT.

package emailmocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailHandlerFunc is an autogenerated mock type for the EmailHandlerFunc type
type MockEmailHandlerFunc struct {
	mock.Mock
}

type MockEmailHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailHandlerFunc) EXPECT() *MockEmailHandlerFunc_Expecter {
	return &MockEmailHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, data
func (_m *MockEmailHandlerFunc) Execute(ctx context.Context, data io.Reader) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmailHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - data io.Reader
func (_e *MockEmailHandlerFunc_Expecter) Execute(ctx interface{}, data interface{}) *MockEmailHandlerFunc_Execute_Call {
	return &MockEmailHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, data)}
}

func (_c *MockEmailHandlerFunc_Execute_Call) Run(run func(ctx context.Context, data io.Reader)) *MockEmailHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockEmailHandlerFunc_Execute_Call) Return(_a0 error) *MockEmailHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailHandlerFunc_Execute_Call) RunAndReturn(run func(context.Context, io.Reader) error) *MockEmailHandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailHandlerFunc creates a new instance of MockEmailHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailHandlerFunc {
	mock := &MockEmailHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
