// Code generated by mockery. DO NOT EDIT.

package emailmocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "go.lumeweb.com/portal-plugin-abuse/internal/pkg/email/interfaces"

	tls "crypto/tls"
)

// MockIMAPDialer is an autogenerated mock type for the IMAPDialer type
type MockIMAPDialer struct {
	mock.Mock
}

type MockIMAPDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMAPDialer) EXPECT() *MockIMAPDialer_Expecter {
	return &MockIMAPDialer_Expecter{mock: &_m.Mock}
}

// DialTLS provides a mock function with given fields: addr, tlsConfig
func (_m *MockIMAPDialer) DialTLS(addr string, tlsConfig *tls.Config) (interfaces.IMAPClientConn, error) {
	ret := _m.Called(addr, tlsConfig)

	if len(ret) == 0 {
		panic("no return value specified for DialTLS")
	}

	var r0 interfaces.IMAPClientConn
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *tls.Config) (interfaces.IMAPClientConn, error)); ok {
		return rf(addr, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, *tls.Config) interfaces.IMAPClientConn); ok {
		r0 = rf(addr, tlsConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.IMAPClientConn)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *tls.Config) error); ok {
		r1 = rf(addr, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMAPDialer_DialTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialTLS'
type MockIMAPDialer_DialTLS_Call struct {
	*mock.Call
}

// DialTLS is a helper method to define mock.On call
//   - addr string
//   - tlsConfig *tls.Config
func (_e *MockIMAPDialer_Expecter) DialTLS(addr interface{}, tlsConfig interface{}) *MockIMAPDialer_DialTLS_Call {
	return &MockIMAPDialer_DialTLS_Call{Call: _e.mock.On("DialTLS", addr, tlsConfig)}
}

func (_c *MockIMAPDialer_DialTLS_Call) Run(run func(addr string, tlsConfig *tls.Config)) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*tls.Config))
	})
	return _c
}

func (_c *MockIMAPDialer_DialTLS_Call) Return(_a0 interfaces.IMAPClientConn, _a1 error) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMAPDialer_DialTLS_Call) RunAndReturn(run func(string, *tls.Config) (interfaces.IMAPClientConn, error)) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMAPDialer creates a new instance of MockIMAPDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMAPDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMAPDialer {
	mock := &MockIMAPDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
