// Code generated by mockery. DO NOT EDIT.

package emailmocks

import (
	imap "github.com/emersion/go-imap"

	mock "github.com/stretchr/testify/mock"
)

// MockIMAPClientConn is an autogenerated mock type for the IMAPClientConn type
type MockIMAPClientConn struct {
	mock.Mock
}

type MockIMAPClientConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMAPClientConn) EXPECT() *MockIMAPClientConn_Expecter {
	return &MockIMAPClientConn_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: seqSet, items, ch
func (_m *MockIMAPClientConn) Fetch(seqSet *imap.SeqSet, items []imap.FetchItem, ch chan *imap.Message) error {
	ret := _m.Called(seqSet, items, ch)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*imap.SeqSet, []imap.FetchItem, chan *imap.Message) error); ok {
		r0 = rf(seqSet, items, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMAPClientConn_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIMAPClientConn_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - seqSet *imap.SeqSet
//   - items []imap.FetchItem
//   - ch chan *imap.Message
func (_e *MockIMAPClientConn_Expecter) Fetch(seqSet interface{}, items interface{}, ch interface{}) *MockIMAPClientConn_Fetch_Call {
	return &MockIMAPClientConn_Fetch_Call{Call: _e.mock.On("Fetch", seqSet, items, ch)}
}

func (_c *MockIMAPClientConn_Fetch_Call) Run(run func(seqSet *imap.SeqSet, items []imap.FetchItem, ch chan *imap.Message)) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*imap.SeqSet), args[1].([]imap.FetchItem), args[2].(chan *imap.Message))
	})
	return _c
}

func (_c *MockIMAPClientConn_Fetch_Call) Return(_a0 error) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMAPClientConn_Fetch_Call) RunAndReturn(run func(*imap.SeqSet, []imap.FetchItem, chan *imap.Message) error) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: username, password
func (_m *MockIMAPClientConn) Login(username string, password string) error {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMAPClientConn_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIMAPClientConn_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockIMAPClientConn_Expecter) Login(username interface{}, password interface{}) *MockIMAPClientConn_Login_Call {
	return &MockIMAPClientConn_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockIMAPClientConn_Login_Call) Run(run func(username string, password string)) *MockIMAPClientConn_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIMAPClientConn_Login_Call) Return(_a0 error) *MockIMAPClientConn_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMAPClientConn_Login_Call) RunAndReturn(run func(string, string) error) *MockIMAPClientConn_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with no fields
func (_m *MockIMAPClientConn) Logout() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMAPClientConn_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIMAPClientConn_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockIMAPClientConn_Expecter) Logout() *MockIMAPClientConn_Logout_Call {
	return &MockIMAPClientConn_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockIMAPClientConn_Logout_Call) Run(run func()) *MockIMAPClientConn_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMAPClientConn_Logout_Call) Return(_a0 error) *MockIMAPClientConn_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMAPClientConn_Logout_Call) RunAndReturn(run func() error) *MockIMAPClientConn_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: criteria
func (_m *MockIMAPClientConn) Search(criteria *imap.SearchCriteria) ([]uint32, error) {
	ret := _m.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(*imap.SearchCriteria) ([]uint32, error)); ok {
		return rf(criteria)
	}
	if rf, ok := ret.Get(0).(func(*imap.SearchCriteria) []uint32); ok {
		r0 = rf(criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}

	if rf, ok := ret.Get(1).(func(*imap.SearchCriteria) error); ok {
		r1 = rf(criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMAPClientConn_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockIMAPClientConn_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - criteria *imap.SearchCriteria
func (_e *MockIMAPClientConn_Expecter) Search(criteria interface{}) *MockIMAPClientConn_Search_Call {
	return &MockIMAPClientConn_Search_Call{Call: _e.mock.On("Search", criteria)}
}

func (_c *MockIMAPClientConn_Search_Call) Run(run func(criteria *imap.SearchCriteria)) *MockIMAPClientConn_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*imap.SearchCriteria))
	})
	return _c
}

func (_c *MockIMAPClientConn_Search_Call) Return(_a0 []uint32, _a1 error) *MockIMAPClientConn_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMAPClientConn_Search_Call) RunAndReturn(run func(*imap.SearchCriteria) ([]uint32, error)) *MockIMAPClientConn_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: mailbox, readOnly
func (_m *MockIMAPClientConn) Select(mailbox string, readOnly bool) (*imap.MailboxStatus, error) {
	ret := _m.Called(mailbox, readOnly)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 *imap.MailboxStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*imap.MailboxStatus, error)); ok {
		return rf(mailbox, readOnly)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *imap.MailboxStatus); ok {
		r0 = rf(mailbox, readOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imap.MailboxStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(mailbox, readOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMAPClientConn_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockIMAPClientConn_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - mailbox string
//   - readOnly bool
func (_e *MockIMAPClientConn_Expecter) Select(mailbox interface{}, readOnly interface{}) *MockIMAPClientConn_Select_Call {
	return &MockIMAPClientConn_Select_Call{Call: _e.mock.On("Select", mailbox, readOnly)}
}

func (_c *MockIMAPClientConn_Select_Call) Run(run func(mailbox string, readOnly bool)) *MockIMAPClientConn_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockIMAPClientConn_Select_Call) Return(_a0 *imap.MailboxStatus, _a1 error) *MockIMAPClientConn_Select_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMAPClientConn_Select_Call) RunAndReturn(run func(string, bool) (*imap.MailboxStatus, error)) *MockIMAPClientConn_Select_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: seqSet, item, flags, ch
func (_m *MockIMAPClientConn) Store(seqSet *imap.SeqSet, item imap.StoreItem, flags []interface{}, ch chan *imap.Message) error {
	ret := _m.Called(seqSet, item, flags, ch)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*imap.SeqSet, imap.StoreItem, []interface{}, chan *imap.Message) error); ok {
		r0 = rf(seqSet, item, flags, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMAPClientConn_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIMAPClientConn_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - seqSet *imap.SeqSet
//   - item imap.StoreItem
//   - flags []interface{}
//   - ch chan *imap.Message
func (_e *MockIMAPClientConn_Expecter) Store(seqSet interface{}, item interface{}, flags interface{}, ch interface{}) *MockIMAPClientConn_Store_Call {
	return &MockIMAPClientConn_Store_Call{Call: _e.mock.On("Store", seqSet, item, flags, ch)}
}

func (_c *MockIMAPClientConn_Store_Call) Run(run func(seqSet *imap.SeqSet, item imap.StoreItem, flags []interface{}, ch chan *imap.Message)) *MockIMAPClientConn_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*imap.SeqSet), args[1].(imap.StoreItem), args[2].([]interface{}), args[3].(chan *imap.Message))
	})
	return _c
}

func (_c *MockIMAPClientConn_Store_Call) Return(_a0 error) *MockIMAPClientConn_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMAPClientConn_Store_Call) RunAndReturn(run func(*imap.SeqSet, imap.StoreItem, []interface{}, chan *imap.Message) error) *MockIMAPClientConn_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMAPClientConn creates a new instance of MockIMAPClientConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMAPClientConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMAPClientConn {
	mock := &MockIMAPClientConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
