// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
)

// NewMockAbuseReportService creates a new instance of MockAbuseReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAbuseReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAbuseReportService {
	mock := &MockAbuseReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAbuseReportService is an autogenerated mock type for the AbuseReportService type
type MockAbuseReportService struct {
	mock.Mock
}

type MockAbuseReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAbuseReportService) EXPECT() *MockAbuseReportService_Expecter {
	return &MockAbuseReportService_Expecter{mock: &_m.Mock}
}

// GetReportStatus provides a mock function for the type MockAbuseReportService
func (_mock *MockAbuseReportService) GetReportStatus(ctx context.Context, confirmationNumber string) (*models.Case, error) {
	ret := _mock.Called(ctx, confirmationNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetReportStatus")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Case, error)); ok {
		return returnFunc(ctx, confirmationNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Case); ok {
		r0 = returnFunc(ctx, confirmationNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, confirmationNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAbuseReportService_GetReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportStatus'
type MockAbuseReportService_GetReportStatus_Call struct {
	*mock.Call
}

// GetReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmationNumber string
func (_e *MockAbuseReportService_Expecter) GetReportStatus(ctx interface{}, confirmationNumber interface{}) *MockAbuseReportService_GetReportStatus_Call {
	return &MockAbuseReportService_GetReportStatus_Call{Call: _e.mock.On("GetReportStatus", ctx, confirmationNumber)}
}

func (_c *MockAbuseReportService_GetReportStatus_Call) Run(run func(ctx context.Context, confirmationNumber string)) *MockAbuseReportService_GetReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAbuseReportService_GetReportStatus_Call) Return(caseParam *models.Case, err error) *MockAbuseReportService_GetReportStatus_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockAbuseReportService_GetReportStatus_Call) RunAndReturn(run func(ctx context.Context, confirmationNumber string) (*models.Case, error)) *MockAbuseReportService_GetReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockAbuseReportService
func (_mock *MockAbuseReportService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAbuseReportService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAbuseReportService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAbuseReportService_Expecter) ID() *MockAbuseReportService_ID_Call {
	return &MockAbuseReportService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAbuseReportService_ID_Call) Run(run func()) *MockAbuseReportService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAbuseReportService_ID_Call) Return(s string) *MockAbuseReportService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAbuseReportService_ID_Call) RunAndReturn(run func() string) *MockAbuseReportService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitReport provides a mock function for the type MockAbuseReportService
func (_mock *MockAbuseReportService) SubmitReport(ctx context.Context, caseData *models.Case) (*models.Case, error) {
	ret := _mock.Called(ctx, caseData)

	if len(ret) == 0 {
		panic("no return value specified for SubmitReport")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Case) (*models.Case, error)); ok {
		return returnFunc(ctx, caseData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Case) *models.Case); ok {
		r0 = returnFunc(ctx, caseData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Case) error); ok {
		r1 = returnFunc(ctx, caseData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAbuseReportService_SubmitReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitReport'
type MockAbuseReportService_SubmitReport_Call struct {
	*mock.Call
}

// SubmitReport is a helper method to define mock.On call
//   - ctx context.Context
//   - caseData *models.Case
func (_e *MockAbuseReportService_Expecter) SubmitReport(ctx interface{}, caseData interface{}) *MockAbuseReportService_SubmitReport_Call {
	return &MockAbuseReportService_SubmitReport_Call{Call: _e.mock.On("SubmitReport", ctx, caseData)}
}

func (_c *MockAbuseReportService_SubmitReport_Call) Run(run func(ctx context.Context, caseData *models.Case)) *MockAbuseReportService_SubmitReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Case
		if args[1] != nil {
			arg1 = args[1].(*models.Case)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAbuseReportService_SubmitReport_Call) Return(caseParam *models.Case, err error) *MockAbuseReportService_SubmitReport_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockAbuseReportService_SubmitReport_Call) RunAndReturn(run func(ctx context.Context, caseData *models.Case) (*models.Case, error)) *MockAbuseReportService_SubmitReport_Call {
	_c.Call.Return(run)
	return _c
}
