// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	models0 "go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/portal-plugin-abuse/internal/types/service"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/portal/db/models"
	"go.lumeweb.com/queryutil"
)

// NewMockBlockListService creates a new instance of MockBlockListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockListService {
	mock := &MockBlockListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockListService is an autogenerated mock type for the BlockListService type
type MockBlockListService struct {
	mock.Mock
}

type MockBlockListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockListService) EXPECT() *MockBlockListService_Expecter {
	return &MockBlockListService_Expecter{mock: &_m.Mock}
}

// BatchBlockFromScanResults provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) BatchBlockFromScanResults(ctx context.Context, scanResults []*models.ScanResult, defaultReason models0.BlockReason, defaultSeverity models0.BlockSeverity, defaultAction models0.BlockAction, source models0.BlockSource) (int, error) {
	ret := _mock.Called(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)

	if len(ret) == 0 {
		panic("no return value specified for BatchBlockFromScanResults")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.ScanResult, models0.BlockReason, models0.BlockSeverity, models0.BlockAction, models0.BlockSource) (int, error)); ok {
		return returnFunc(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.ScanResult, models0.BlockReason, models0.BlockSeverity, models0.BlockAction, models0.BlockSource) int); ok {
		r0 = returnFunc(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*models.ScanResult, models0.BlockReason, models0.BlockSeverity, models0.BlockAction, models0.BlockSource) error); ok {
		r1 = returnFunc(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_BatchBlockFromScanResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchBlockFromScanResults'
type MockBlockListService_BatchBlockFromScanResults_Call struct {
	*mock.Call
}

// BatchBlockFromScanResults is a helper method to define mock.On call
//   - ctx context.Context
//   - scanResults []*models.ScanResult
//   - defaultReason models0.BlockReason
//   - defaultSeverity models0.BlockSeverity
//   - defaultAction models0.BlockAction
//   - source models0.BlockSource
func (_e *MockBlockListService_Expecter) BatchBlockFromScanResults(ctx interface{}, scanResults interface{}, defaultReason interface{}, defaultSeverity interface{}, defaultAction interface{}, source interface{}) *MockBlockListService_BatchBlockFromScanResults_Call {
	return &MockBlockListService_BatchBlockFromScanResults_Call{Call: _e.mock.On("BatchBlockFromScanResults", ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)}
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) Run(run func(ctx context.Context, scanResults []*models.ScanResult, defaultReason models0.BlockReason, defaultSeverity models0.BlockSeverity, defaultAction models0.BlockAction, source models0.BlockSource)) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.ScanResult
		if args[1] != nil {
			arg1 = args[1].([]*models.ScanResult)
		}
		var arg2 models0.BlockReason
		if args[2] != nil {
			arg2 = args[2].(models0.BlockReason)
		}
		var arg3 models0.BlockSeverity
		if args[3] != nil {
			arg3 = args[3].(models0.BlockSeverity)
		}
		var arg4 models0.BlockAction
		if args[4] != nil {
			arg4 = args[4].(models0.BlockAction)
		}
		var arg5 models0.BlockSource
		if args[5] != nil {
			arg5 = args[5].(models0.BlockSource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) Return(n int, err error) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) RunAndReturn(run func(ctx context.Context, scanResults []*models.ScanResult, defaultReason models0.BlockReason, defaultSeverity models0.BlockSeverity, defaultAction models0.BlockAction, source models0.BlockSource) (int, error)) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Return(run)
	return _c
}

// BlockContent provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) BlockContent(block *models0.BlockList) (*models0.BlockList, error) {
	ret := _mock.Called(block)

	if len(ret) == 0 {
		panic("no return value specified for BlockContent")
	}

	var r0 *models0.BlockList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models0.BlockList) (*models0.BlockList, error)); ok {
		return returnFunc(block)
	}
	if returnFunc, ok := ret.Get(0).(func(*models0.BlockList) *models0.BlockList); ok {
		r0 = returnFunc(block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models0.BlockList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models0.BlockList) error); ok {
		r1 = returnFunc(block)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_BlockContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockContent'
type MockBlockListService_BlockContent_Call struct {
	*mock.Call
}

// BlockContent is a helper method to define mock.On call
//   - block *models0.BlockList
func (_e *MockBlockListService_Expecter) BlockContent(block interface{}) *MockBlockListService_BlockContent_Call {
	return &MockBlockListService_BlockContent_Call{Call: _e.mock.On("BlockContent", block)}
}

func (_c *MockBlockListService_BlockContent_Call) Run(run func(block *models0.BlockList)) *MockBlockListService_BlockContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models0.BlockList
		if args[0] != nil {
			arg0 = args[0].(*models0.BlockList)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_BlockContent_Call) Return(blockList *models0.BlockList, err error) *MockBlockListService_BlockContent_Call {
	_c.Call.Return(blockList, err)
	return _c
}

func (_c *MockBlockListService_BlockContent_Call) RunAndReturn(run func(block *models0.BlockList) (*models0.BlockList, error)) *MockBlockListService_BlockContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockReasonCounts provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) GetBlockReasonCounts(filters []queryutil.CrudFilter) ([]service.BlockReasonCount, error) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockReasonCounts")
	}

	var r0 []service.BlockReasonCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) ([]service.BlockReasonCount, error)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) []service.BlockReasonCount); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.BlockReasonCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter) error); ok {
		r1 = returnFunc(filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_GetBlockReasonCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockReasonCounts'
type MockBlockListService_GetBlockReasonCounts_Call struct {
	*mock.Call
}

// GetBlockReasonCounts is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
func (_e *MockBlockListService_Expecter) GetBlockReasonCounts(filters interface{}) *MockBlockListService_GetBlockReasonCounts_Call {
	return &MockBlockListService_GetBlockReasonCounts_Call{Call: _e.mock.On("GetBlockReasonCounts", filters)}
}

func (_c *MockBlockListService_GetBlockReasonCounts_Call) Run(run func(filters []queryutil.CrudFilter)) *MockBlockListService_GetBlockReasonCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_GetBlockReasonCounts_Call) Return(blockReasonCounts []service.BlockReasonCount, err error) *MockBlockListService_GetBlockReasonCounts_Call {
	_c.Call.Return(blockReasonCounts, err)
	return _c
}

func (_c *MockBlockListService_GetBlockReasonCounts_Call) RunAndReturn(run func(filters []queryutil.CrudFilter) ([]service.BlockReasonCount, error)) *MockBlockListService_GetBlockReasonCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedContent provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) GetBlockedContent(hash core.StorageHash) (*models0.BlockList, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedContent")
	}

	var r0 *models0.BlockList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) (*models0.BlockList, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) *models0.BlockList); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models0.BlockList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.StorageHash) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_GetBlockedContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedContent'
type MockBlockListService_GetBlockedContent_Call struct {
	*mock.Call
}

// GetBlockedContent is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) GetBlockedContent(hash interface{}) *MockBlockListService_GetBlockedContent_Call {
	return &MockBlockListService_GetBlockedContent_Call{Call: _e.mock.On("GetBlockedContent", hash)}
}

func (_c *MockBlockListService_GetBlockedContent_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_GetBlockedContent_Call) Return(blockList *models0.BlockList, err error) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Return(blockList, err)
	return _c
}

func (_c *MockBlockListService_GetBlockedContent_Call) RunAndReturn(run func(hash core.StorageHash) (*models0.BlockList, error)) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocklistMetrics provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) GetBlocklistMetrics(filters []queryutil.CrudFilter) (*service.BlocklistAnalytics, error) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocklistMetrics")
	}

	var r0 *service.BlocklistAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) (*service.BlocklistAnalytics, error)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) *service.BlocklistAnalytics); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.BlocklistAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter) error); ok {
		r1 = returnFunc(filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_GetBlocklistMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocklistMetrics'
type MockBlockListService_GetBlocklistMetrics_Call struct {
	*mock.Call
}

// GetBlocklistMetrics is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
func (_e *MockBlockListService_Expecter) GetBlocklistMetrics(filters interface{}) *MockBlockListService_GetBlocklistMetrics_Call {
	return &MockBlockListService_GetBlocklistMetrics_Call{Call: _e.mock.On("GetBlocklistMetrics", filters)}
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) Run(run func(filters []queryutil.CrudFilter)) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) Return(blocklistAnalytics *service.BlocklistAnalytics, err error) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Return(blocklistAnalytics, err)
	return _c
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) RunAndReturn(run func(filters []queryutil.CrudFilter) (*service.BlocklistAnalytics, error)) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksByCaseID provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) GetBlocksByCaseID(caseID uint) ([]models0.BlockList, error) {
	ret := _mock.Called(caseID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksByCaseID")
	}

	var r0 []models0.BlockList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]models0.BlockList, error)); ok {
		return returnFunc(caseID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []models0.BlockList); ok {
		r0 = returnFunc(caseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models0.BlockList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(caseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_GetBlocksByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksByCaseID'
type MockBlockListService_GetBlocksByCaseID_Call struct {
	*mock.Call
}

// GetBlocksByCaseID is a helper method to define mock.On call
//   - caseID uint
func (_e *MockBlockListService_Expecter) GetBlocksByCaseID(caseID interface{}) *MockBlockListService_GetBlocksByCaseID_Call {
	return &MockBlockListService_GetBlocksByCaseID_Call{Call: _e.mock.On("GetBlocksByCaseID", caseID)}
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) Run(run func(caseID uint)) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) Return(blockLists []models0.BlockList, err error) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Return(blockLists, err)
	return _c
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) RunAndReturn(run func(caseID uint) ([]models0.BlockList, error)) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBlockListService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBlockListService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBlockListService_Expecter) ID() *MockBlockListService_ID_Call {
	return &MockBlockListService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBlockListService_ID_Call) Run(run func()) *MockBlockListService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockListService_ID_Call) Return(s string) *MockBlockListService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBlockListService_ID_Call) RunAndReturn(run func() string) *MockBlockListService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlocked provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) IsBlocked(hash core.StorageHash) (bool, *models0.BlockList, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 *models0.BlockList
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) (bool, *models0.BlockList, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(core.StorageHash) *models0.BlockList); ok {
		r1 = returnFunc(hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models0.BlockList)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(core.StorageHash) error); ok {
		r2 = returnFunc(hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBlockListService_IsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlocked'
type MockBlockListService_IsBlocked_Call struct {
	*mock.Call
}

// IsBlocked is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) IsBlocked(hash interface{}) *MockBlockListService_IsBlocked_Call {
	return &MockBlockListService_IsBlocked_Call{Call: _e.mock.On("IsBlocked", hash)}
}

func (_c *MockBlockListService_IsBlocked_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_IsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_IsBlocked_Call) Return(b bool, blockList *models0.BlockList, err error) *MockBlockListService_IsBlocked_Call {
	_c.Call.Return(b, blockList, err)
	return _c
}

func (_c *MockBlockListService_IsBlocked_Call) RunAndReturn(run func(hash core.StorageHash) (bool, *models0.BlockList, error)) *MockBlockListService_IsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// IsSubjectBlocked provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) IsSubjectBlocked(subjectID uint) (bool, error) {
	ret := _mock.Called(subjectID)

	if len(ret) == 0 {
		panic("no return value specified for IsSubjectBlocked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return returnFunc(subjectID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = returnFunc(subjectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(subjectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockListService_IsSubjectBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSubjectBlocked'
type MockBlockListService_IsSubjectBlocked_Call struct {
	*mock.Call
}

// IsSubjectBlocked is a helper method to define mock.On call
//   - subjectID uint
func (_e *MockBlockListService_Expecter) IsSubjectBlocked(subjectID interface{}) *MockBlockListService_IsSubjectBlocked_Call {
	return &MockBlockListService_IsSubjectBlocked_Call{Call: _e.mock.On("IsSubjectBlocked", subjectID)}
}

func (_c *MockBlockListService_IsSubjectBlocked_Call) Run(run func(subjectID uint)) *MockBlockListService_IsSubjectBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_IsSubjectBlocked_Call) Return(b bool, err error) *MockBlockListService_IsSubjectBlocked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlockListService_IsSubjectBlocked_Call) RunAndReturn(run func(subjectID uint) (bool, error)) *MockBlockListService_IsSubjectBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// ListBlockedContent provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) ListBlockedContent(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models0.BlockList, int64, error) {
	ret := _mock.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListBlockedContent")
	}

	var r0 []models0.BlockList
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models0.BlockList, int64, error)); ok {
		return returnFunc(filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models0.BlockList); ok {
		r0 = returnFunc(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models0.BlockList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBlockListService_ListBlockedContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBlockedContent'
type MockBlockListService_ListBlockedContent_Call struct {
	*mock.Call
}

// ListBlockedContent is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockBlockListService_Expecter) ListBlockedContent(filters interface{}, sorts interface{}, pagination interface{}) *MockBlockListService_ListBlockedContent_Call {
	return &MockBlockListService_ListBlockedContent_Call{Call: _e.mock.On("ListBlockedContent", filters, sorts, pagination)}
}

func (_c *MockBlockListService_ListBlockedContent_Call) Run(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		var arg1 []queryutil.Sort
		if args[1] != nil {
			arg1 = args[1].([]queryutil.Sort)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlockListService_ListBlockedContent_Call) Return(blockLists []models0.BlockList, n int64, err error) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Return(blockLists, n, err)
	return _c
}

func (_c *MockBlockListService_ListBlockedContent_Call) RunAndReturn(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models0.BlockList, int64, error)) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockContent provides a mock function for the type MockBlockListService
func (_mock *MockBlockListService) UnblockContent(hash core.StorageHash) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for UnblockContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockListService_UnblockContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockContent'
type MockBlockListService_UnblockContent_Call struct {
	*mock.Call
}

// UnblockContent is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) UnblockContent(hash interface{}) *MockBlockListService_UnblockContent_Call {
	return &MockBlockListService_UnblockContent_Call{Call: _e.mock.On("UnblockContent", hash)}
}

func (_c *MockBlockListService_UnblockContent_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_UnblockContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockListService_UnblockContent_Call) Return(err error) *MockBlockListService_UnblockContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockListService_UnblockContent_Call) RunAndReturn(run func(hash core.StorageHash) error) *MockBlockListService_UnblockContent_Call {
	_c.Call.Return(run)
	return _c
}
