// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dbmodels "go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	core "go.lumeweb.com/portal/core"

	mock "github.com/stretchr/testify/mock"

	models "go.lumeweb.com/portal/db/models"

	queryutil "go.lumeweb.com/queryutil"

	service "go.lumeweb.com/portal-plugin-abuse/internal/types/service"

	time "time"
)

// MockBlockListService is an autogenerated mock type for the BlockListService type
type MockBlockListService struct {
	mock.Mock
}

type MockBlockListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockListService) EXPECT() *MockBlockListService_Expecter {
	return &MockBlockListService_Expecter{mock: &_m.Mock}
}

// BatchBlockFromScanResults provides a mock function with given fields: ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source
func (_m *MockBlockListService) BatchBlockFromScanResults(ctx context.Context, scanResults []*models.ScanResult, defaultReason string, defaultSeverity string, defaultAction string, source string) (int, error) {
	ret := _m.Called(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)

	if len(ret) == 0 {
		panic("no return value specified for BatchBlockFromScanResults")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ScanResult, string, string, string, string) (int, error)); ok {
		return rf(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ScanResult, string, string, string, string) int); ok {
		r0 = rf(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.ScanResult, string, string, string, string) error); ok {
		r1 = rf(ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockListService_BatchBlockFromScanResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchBlockFromScanResults'
type MockBlockListService_BatchBlockFromScanResults_Call struct {
	*mock.Call
}

// BatchBlockFromScanResults is a helper method to define mock.On call
//   - ctx context.Context
//   - scanResults []*models.ScanResult
//   - defaultReason string
//   - defaultSeverity string
//   - defaultAction string
//   - source string
func (_e *MockBlockListService_Expecter) BatchBlockFromScanResults(ctx interface{}, scanResults interface{}, defaultReason interface{}, defaultSeverity interface{}, defaultAction interface{}, source interface{}) *MockBlockListService_BatchBlockFromScanResults_Call {
	return &MockBlockListService_BatchBlockFromScanResults_Call{Call: _e.mock.On("BatchBlockFromScanResults", ctx, scanResults, defaultReason, defaultSeverity, defaultAction, source)}
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) Run(run func(ctx context.Context, scanResults []*models.ScanResult, defaultReason string, defaultSeverity string, defaultAction string, source string)) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.ScanResult), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) Return(_a0 int, _a1 error) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockListService_BatchBlockFromScanResults_Call) RunAndReturn(run func(context.Context, []*models.ScanResult, string, string, string, string) (int, error)) *MockBlockListService_BatchBlockFromScanResults_Call {
	_c.Call.Return(run)
	return _c
}

// BlockContent provides a mock function with given fields: block
func (_m *MockBlockListService) BlockContent(block *dbmodels.BlockList) (*dbmodels.BlockList, error) {
	ret := _m.Called(block)

	if len(ret) == 0 {
		panic("no return value specified for BlockContent")
	}

	var r0 *dbmodels.BlockList
	var r1 error
	if rf, ok := ret.Get(0).(func(*dbmodels.BlockList) (*dbmodels.BlockList, error)); ok {
		return rf(block)
	}
	if rf, ok := ret.Get(0).(func(*dbmodels.BlockList) *dbmodels.BlockList); ok {
		r0 = rf(block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.BlockList)
		}
	}

	if rf, ok := ret.Get(1).(func(*dbmodels.BlockList) error); ok {
		r1 = rf(block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockListService_BlockContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockContent'
type MockBlockListService_BlockContent_Call struct {
	*mock.Call
}

// BlockContent is a helper method to define mock.On call
//   - block *dbmodels.BlockList
func (_e *MockBlockListService_Expecter) BlockContent(block interface{}) *MockBlockListService_BlockContent_Call {
	return &MockBlockListService_BlockContent_Call{Call: _e.mock.On("BlockContent", block)}
}

func (_c *MockBlockListService_BlockContent_Call) Run(run func(block *dbmodels.BlockList)) *MockBlockListService_BlockContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dbmodels.BlockList))
	})
	return _c
}

func (_c *MockBlockListService_BlockContent_Call) Return(_a0 *dbmodels.BlockList, _a1 error) *MockBlockListService_BlockContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockListService_BlockContent_Call) RunAndReturn(run func(*dbmodels.BlockList) (*dbmodels.BlockList, error)) *MockBlockListService_BlockContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedContent provides a mock function with given fields: hash
func (_m *MockBlockListService) GetBlockedContent(hash core.StorageHash) (*dbmodels.BlockList, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedContent")
	}

	var r0 *dbmodels.BlockList
	var r1 error
	if rf, ok := ret.Get(0).(func(core.StorageHash) (*dbmodels.BlockList, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(core.StorageHash) *dbmodels.BlockList); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.BlockList)
		}
	}

	if rf, ok := ret.Get(1).(func(core.StorageHash) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockListService_GetBlockedContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedContent'
type MockBlockListService_GetBlockedContent_Call struct {
	*mock.Call
}

// GetBlockedContent is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) GetBlockedContent(hash interface{}) *MockBlockListService_GetBlockedContent_Call {
	return &MockBlockListService_GetBlockedContent_Call{Call: _e.mock.On("GetBlockedContent", hash)}
}

func (_c *MockBlockListService_GetBlockedContent_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.StorageHash))
	})
	return _c
}

func (_c *MockBlockListService_GetBlockedContent_Call) Return(_a0 *dbmodels.BlockList, _a1 error) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockListService_GetBlockedContent_Call) RunAndReturn(run func(core.StorageHash) (*dbmodels.BlockList, error)) *MockBlockListService_GetBlockedContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocklistMetrics provides a mock function with given fields: start, end
func (_m *MockBlockListService) GetBlocklistMetrics(start time.Time, end time.Time) (*service.BlocklistAnalytics, error) {
	ret := _m.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocklistMetrics")
	}

	var r0 *service.BlocklistAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) (*service.BlocklistAnalytics, error)); ok {
		return rf(start, end)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) *service.BlocklistAnalytics); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.BlocklistAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockListService_GetBlocklistMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocklistMetrics'
type MockBlockListService_GetBlocklistMetrics_Call struct {
	*mock.Call
}

// GetBlocklistMetrics is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockBlockListService_Expecter) GetBlocklistMetrics(start interface{}, end interface{}) *MockBlockListService_GetBlocklistMetrics_Call {
	return &MockBlockListService_GetBlocklistMetrics_Call{Call: _e.mock.On("GetBlocklistMetrics", start, end)}
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) Run(run func(start time.Time, end time.Time)) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) Return(_a0 *service.BlocklistAnalytics, _a1 error) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockListService_GetBlocklistMetrics_Call) RunAndReturn(run func(time.Time, time.Time) (*service.BlocklistAnalytics, error)) *MockBlockListService_GetBlocklistMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksByCaseID provides a mock function with given fields: caseID
func (_m *MockBlockListService) GetBlocksByCaseID(caseID uint) ([]dbmodels.BlockList, error) {
	ret := _m.Called(caseID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksByCaseID")
	}

	var r0 []dbmodels.BlockList
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dbmodels.BlockList, error)); ok {
		return rf(caseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dbmodels.BlockList); ok {
		r0 = rf(caseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbmodels.BlockList)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(caseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockListService_GetBlocksByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksByCaseID'
type MockBlockListService_GetBlocksByCaseID_Call struct {
	*mock.Call
}

// GetBlocksByCaseID is a helper method to define mock.On call
//   - caseID uint
func (_e *MockBlockListService_Expecter) GetBlocksByCaseID(caseID interface{}) *MockBlockListService_GetBlocksByCaseID_Call {
	return &MockBlockListService_GetBlocksByCaseID_Call{Call: _e.mock.On("GetBlocksByCaseID", caseID)}
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) Run(run func(caseID uint)) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) Return(_a0 []dbmodels.BlockList, _a1 error) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockListService_GetBlocksByCaseID_Call) RunAndReturn(run func(uint) ([]dbmodels.BlockList, error)) *MockBlockListService_GetBlocksByCaseID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockBlockListService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBlockListService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBlockListService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBlockListService_Expecter) ID() *MockBlockListService_ID_Call {
	return &MockBlockListService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBlockListService_ID_Call) Run(run func()) *MockBlockListService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockListService_ID_Call) Return(_a0 string) *MockBlockListService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockListService_ID_Call) RunAndReturn(run func() string) *MockBlockListService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlocked provides a mock function with given fields: hash
func (_m *MockBlockListService) IsBlocked(hash core.StorageHash) (bool, *dbmodels.BlockList, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 *dbmodels.BlockList
	var r2 error
	if rf, ok := ret.Get(0).(func(core.StorageHash) (bool, *dbmodels.BlockList, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(core.StorageHash) bool); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(core.StorageHash) *dbmodels.BlockList); ok {
		r1 = rf(hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dbmodels.BlockList)
		}
	}

	if rf, ok := ret.Get(2).(func(core.StorageHash) error); ok {
		r2 = rf(hash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBlockListService_IsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlocked'
type MockBlockListService_IsBlocked_Call struct {
	*mock.Call
}

// IsBlocked is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) IsBlocked(hash interface{}) *MockBlockListService_IsBlocked_Call {
	return &MockBlockListService_IsBlocked_Call{Call: _e.mock.On("IsBlocked", hash)}
}

func (_c *MockBlockListService_IsBlocked_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_IsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.StorageHash))
	})
	return _c
}

func (_c *MockBlockListService_IsBlocked_Call) Return(_a0 bool, _a1 *dbmodels.BlockList, _a2 error) *MockBlockListService_IsBlocked_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBlockListService_IsBlocked_Call) RunAndReturn(run func(core.StorageHash) (bool, *dbmodels.BlockList, error)) *MockBlockListService_IsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// ListBlockedContent provides a mock function with given fields: filters, sorts, pagination
func (_m *MockBlockListService) ListBlockedContent(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]dbmodels.BlockList, int64, error) {
	ret := _m.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListBlockedContent")
	}

	var r0 []dbmodels.BlockList
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]dbmodels.BlockList, int64, error)); ok {
		return rf(filters, sorts, pagination)
	}
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) []dbmodels.BlockList); ok {
		r0 = rf(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbmodels.BlockList)
		}
	}

	if rf, ok := ret.Get(1).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = rf(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = rf(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBlockListService_ListBlockedContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBlockedContent'
type MockBlockListService_ListBlockedContent_Call struct {
	*mock.Call
}

// ListBlockedContent is a helper method to define mock.On call
//   - filters []queryutil.Filter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockBlockListService_Expecter) ListBlockedContent(filters interface{}, sorts interface{}, pagination interface{}) *MockBlockListService_ListBlockedContent_Call {
	return &MockBlockListService_ListBlockedContent_Call{Call: _e.mock.On("ListBlockedContent", filters, sorts, pagination)}
}

func (_c *MockBlockListService_ListBlockedContent_Call) Run(run func(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]queryutil.Filter), args[1].([]queryutil.Sort), args[2].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockBlockListService_ListBlockedContent_Call) Return(_a0 []dbmodels.BlockList, _a1 int64, _a2 error) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBlockListService_ListBlockedContent_Call) RunAndReturn(run func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]dbmodels.BlockList, int64, error)) *MockBlockListService_ListBlockedContent_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockContent provides a mock function with given fields: hash
func (_m *MockBlockListService) UnblockContent(hash core.StorageHash) error {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for UnblockContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.StorageHash) error); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlockListService_UnblockContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockContent'
type MockBlockListService_UnblockContent_Call struct {
	*mock.Call
}

// UnblockContent is a helper method to define mock.On call
//   - hash core.StorageHash
func (_e *MockBlockListService_Expecter) UnblockContent(hash interface{}) *MockBlockListService_UnblockContent_Call {
	return &MockBlockListService_UnblockContent_Call{Call: _e.mock.On("UnblockContent", hash)}
}

func (_c *MockBlockListService_UnblockContent_Call) Run(run func(hash core.StorageHash)) *MockBlockListService_UnblockContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.StorageHash))
	})
	return _c
}

func (_c *MockBlockListService_UnblockContent_Call) Return(_a0 error) *MockBlockListService_UnblockContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockListService_UnblockContent_Call) RunAndReturn(run func(core.StorageHash) error) *MockBlockListService_UnblockContent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlockListService creates a new instance of MockBlockListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockListService {
	mock := &MockBlockListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
