// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "go.lumeweb.com/portal-plugin-abuse/internal/db/models"

	queryutil "go.lumeweb.com/queryutil"

	service "go.lumeweb.com/portal-plugin-abuse/internal/types/service"
)

// MockCaseService is an autogenerated mock type for the CaseService type
type MockCaseService struct {
	mock.Mock
}

type MockCaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaseService) EXPECT() *MockCaseService_Expecter {
	return &MockCaseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: caseData
func (_m *MockCaseService) Create(caseData *models.Case) (*models.Case, error) {
	ret := _m.Called(caseData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Case) (*models.Case, error)); ok {
		return rf(caseData)
	}
	if rf, ok := ret.Get(0).(func(*models.Case) *models.Case); ok {
		r0 = rf(caseData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Case) error); ok {
		r1 = rf(caseData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCaseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - caseData *models.Case
func (_e *MockCaseService_Expecter) Create(caseData interface{}) *MockCaseService_Create_Call {
	return &MockCaseService_Create_Call{Call: _e.mock.On("Create", caseData)}
}

func (_c *MockCaseService_Create_Call) Run(run func(caseData *models.Case)) *MockCaseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Case))
	})
	return _c
}

func (_c *MockCaseService_Create_Call) Return(_a0 *models.Case, _a1 error) *MockCaseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_Create_Call) RunAndReturn(run func(*models.Case) (*models.Case, error)) *MockCaseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get30DayAnalytics provides a mock function with no fields
func (_m *MockCaseService) Get30DayAnalytics() (*service.CaseAnalytics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get30DayAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func() (*service.CaseAnalytics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *service.CaseAnalytics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_Get30DayAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get30DayAnalytics'
type MockCaseService_Get30DayAnalytics_Call struct {
	*mock.Call
}

// Get30DayAnalytics is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) Get30DayAnalytics() *MockCaseService_Get30DayAnalytics_Call {
	return &MockCaseService_Get30DayAnalytics_Call{Call: _e.mock.On("Get30DayAnalytics")}
}

func (_c *MockCaseService_Get30DayAnalytics_Call) Run(run func()) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_Get30DayAnalytics_Call) Return(_a0 *service.CaseAnalytics, _a1 error) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_Get30DayAnalytics_Call) RunAndReturn(run func() (*service.CaseAnalytics, error)) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// Get7DayAnalytics provides a mock function with no fields
func (_m *MockCaseService) Get7DayAnalytics() (*service.CaseAnalytics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get7DayAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func() (*service.CaseAnalytics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *service.CaseAnalytics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_Get7DayAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get7DayAnalytics'
type MockCaseService_Get7DayAnalytics_Call struct {
	*mock.Call
}

// Get7DayAnalytics is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) Get7DayAnalytics() *MockCaseService_Get7DayAnalytics_Call {
	return &MockCaseService_Get7DayAnalytics_Call{Call: _e.mock.On("Get7DayAnalytics")}
}

func (_c *MockCaseService_Get7DayAnalytics_Call) Run(run func()) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_Get7DayAnalytics_Call) Return(_a0 *service.CaseAnalytics, _a1 error) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_Get7DayAnalytics_Call) RunAndReturn(run func() (*service.CaseAnalytics, error)) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnalytics provides a mock function with given fields: filters
func (_m *MockCaseService) GetAnalytics(filters []queryutil.Filter) (*service.CaseAnalytics, error) {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func([]queryutil.Filter) (*service.CaseAnalytics, error)); ok {
		return rf(filters)
	}
	if rf, ok := ret.Get(0).(func([]queryutil.Filter) *service.CaseAnalytics); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func([]queryutil.Filter) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_GetAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalytics'
type MockCaseService_GetAnalytics_Call struct {
	*mock.Call
}

// GetAnalytics is a helper method to define mock.On call
//   - filters []queryutil.Filter
func (_e *MockCaseService_Expecter) GetAnalytics(filters interface{}) *MockCaseService_GetAnalytics_Call {
	return &MockCaseService_GetAnalytics_Call{Call: _e.mock.On("GetAnalytics", filters)}
}

func (_c *MockCaseService_GetAnalytics_Call) Run(run func(filters []queryutil.Filter)) *MockCaseService_GetAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]queryutil.Filter))
	})
	return _c
}

func (_c *MockCaseService_GetAnalytics_Call) Return(_a0 *service.CaseAnalytics, _a1 error) *MockCaseService_GetAnalytics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_GetAnalytics_Call) RunAndReturn(run func([]queryutil.Filter) (*service.CaseAnalytics, error)) *MockCaseService_GetAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockCaseService) GetByID(id uint) (*models.Case, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Case, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Case); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCaseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCaseService_Expecter) GetByID(id interface{}) *MockCaseService_GetByID_Call {
	return &MockCaseService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCaseService_GetByID_Call) Run(run func(id uint)) *MockCaseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCaseService_GetByID_Call) Return(_a0 *models.Case, _a1 error) *MockCaseService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_GetByID_Call) RunAndReturn(run func(uint) (*models.Case, error)) *MockCaseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCaseByReference provides a mock function with given fields: reference
func (_m *MockCaseService) GetCaseByReference(reference string) (*models.Case, error) {
	ret := _m.Called(reference)

	if len(ret) == 0 {
		panic("no return value specified for GetCaseByReference")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Case, error)); ok {
		return rf(reference)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Case); ok {
		r0 = rf(reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_GetCaseByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCaseByReference'
type MockCaseService_GetCaseByReference_Call struct {
	*mock.Call
}

// GetCaseByReference is a helper method to define mock.On call
//   - reference string
func (_e *MockCaseService_Expecter) GetCaseByReference(reference interface{}) *MockCaseService_GetCaseByReference_Call {
	return &MockCaseService_GetCaseByReference_Call{Call: _e.mock.On("GetCaseByReference", reference)}
}

func (_c *MockCaseService_GetCaseByReference_Call) Run(run func(reference string)) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCaseService_GetCaseByReference_Call) Return(_a0 *models.Case, _a1 error) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_GetCaseByReference_Call) RunAndReturn(run func(string) (*models.Case, error)) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicCase provides a mock function with given fields: reference, reporterID
func (_m *MockCaseService) GetPublicCase(reference string, reporterID uint) (*models.Case, error) {
	ret := _m.Called(reference, reporterID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCase")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint) (*models.Case, error)); ok {
		return rf(reference, reporterID)
	}
	if rf, ok := ret.Get(0).(func(string, uint) *models.Case); ok {
		r0 = rf(reference, reporterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(reference, reporterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCaseService_GetPublicCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicCase'
type MockCaseService_GetPublicCase_Call struct {
	*mock.Call
}

// GetPublicCase is a helper method to define mock.On call
//   - reference string
//   - reporterID uint
func (_e *MockCaseService_Expecter) GetPublicCase(reference interface{}, reporterID interface{}) *MockCaseService_GetPublicCase_Call {
	return &MockCaseService_GetPublicCase_Call{Call: _e.mock.On("GetPublicCase", reference, reporterID)}
}

func (_c *MockCaseService_GetPublicCase_Call) Run(run func(reference string, reporterID uint)) *MockCaseService_GetPublicCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint))
	})
	return _c
}

func (_c *MockCaseService_GetPublicCase_Call) Return(_a0 *models.Case, _a1 error) *MockCaseService_GetPublicCase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCaseService_GetPublicCase_Call) RunAndReturn(run func(string, uint) (*models.Case, error)) *MockCaseService_GetPublicCase_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockCaseService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCaseService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCaseService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) ID() *MockCaseService_ID_Call {
	return &MockCaseService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCaseService_ID_Call) Run(run func()) *MockCaseService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_ID_Call) Return(_a0 string) *MockCaseService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_ID_Call) RunAndReturn(run func() string) *MockCaseService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// LinkSubject provides a mock function with given fields: caseID, subjectID
func (_m *MockCaseService) LinkSubject(caseID uint, subjectID uint) error {
	ret := _m.Called(caseID, subjectID)

	if len(ret) == 0 {
		panic("no return value specified for LinkSubject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(caseID, subjectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaseService_LinkSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkSubject'
type MockCaseService_LinkSubject_Call struct {
	*mock.Call
}

// LinkSubject is a helper method to define mock.On call
//   - caseID uint
//   - subjectID uint
func (_e *MockCaseService_Expecter) LinkSubject(caseID interface{}, subjectID interface{}) *MockCaseService_LinkSubject_Call {
	return &MockCaseService_LinkSubject_Call{Call: _e.mock.On("LinkSubject", caseID, subjectID)}
}

func (_c *MockCaseService_LinkSubject_Call) Run(run func(caseID uint, subjectID uint)) *MockCaseService_LinkSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockCaseService_LinkSubject_Call) Return(_a0 error) *MockCaseService_LinkSubject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_LinkSubject_Call) RunAndReturn(run func(uint, uint) error) *MockCaseService_LinkSubject_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: filters, sorts, pagination
func (_m *MockCaseService) List(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Case, int64, error) {
	ret := _m.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Case
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Case, int64, error)); ok {
		return rf(filters, sorts, pagination)
	}
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) []models.Case); ok {
		r0 = rf(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = rf(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = rf(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCaseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCaseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filters []queryutil.Filter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockCaseService_Expecter) List(filters interface{}, sorts interface{}, pagination interface{}) *MockCaseService_List_Call {
	return &MockCaseService_List_Call{Call: _e.mock.On("List", filters, sorts, pagination)}
}

func (_c *MockCaseService_List_Call) Run(run func(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockCaseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]queryutil.Filter), args[1].([]queryutil.Sort), args[2].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockCaseService_List_Call) Return(_a0 []models.Case, _a1 int64, _a2 error) *MockCaseService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCaseService_List_Call) RunAndReturn(run func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Case, int64, error)) *MockCaseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, filters, pagination
func (_m *MockCaseService) Search(ctx context.Context, query string, filters []queryutil.Filter, pagination queryutil.Pagination) ([]models.Case, int64, error) {
	ret := _m.Called(ctx, query, filters, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []models.Case
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []queryutil.Filter, queryutil.Pagination) ([]models.Case, int64, error)); ok {
		return rf(ctx, query, filters, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []queryutil.Filter, queryutil.Pagination) []models.Case); ok {
		r0 = rf(ctx, query, filters, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []queryutil.Filter, queryutil.Pagination) int64); ok {
		r1 = rf(ctx, query, filters, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []queryutil.Filter, queryutil.Pagination) error); ok {
		r2 = rf(ctx, query, filters, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCaseService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCaseService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters []queryutil.Filter
//   - pagination queryutil.Pagination
func (_e *MockCaseService_Expecter) Search(ctx interface{}, query interface{}, filters interface{}, pagination interface{}) *MockCaseService_Search_Call {
	return &MockCaseService_Search_Call{Call: _e.mock.On("Search", ctx, query, filters, pagination)}
}

func (_c *MockCaseService_Search_Call) Run(run func(ctx context.Context, query string, filters []queryutil.Filter, pagination queryutil.Pagination)) *MockCaseService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]queryutil.Filter), args[3].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockCaseService_Search_Call) Return(_a0 []models.Case, _a1 int64, _a2 error) *MockCaseService_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCaseService_Search_Call) RunAndReturn(run func(context.Context, string, []queryutil.Filter, queryutil.Pagination) ([]models.Case, int64, error)) *MockCaseService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SendCreationNotification provides a mock function with given fields: caseID
func (_m *MockCaseService) SendCreationNotification(caseID uint) error {
	ret := _m.Called(caseID)

	if len(ret) == 0 {
		panic("no return value specified for SendCreationNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(caseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaseService_SendCreationNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCreationNotification'
type MockCaseService_SendCreationNotification_Call struct {
	*mock.Call
}

// SendCreationNotification is a helper method to define mock.On call
//   - caseID uint
func (_e *MockCaseService_Expecter) SendCreationNotification(caseID interface{}) *MockCaseService_SendCreationNotification_Call {
	return &MockCaseService_SendCreationNotification_Call{Call: _e.mock.On("SendCreationNotification", caseID)}
}

func (_c *MockCaseService_SendCreationNotification_Call) Run(run func(caseID uint)) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCaseService_SendCreationNotification_Call) Return(_a0 error) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_SendCreationNotification_Call) RunAndReturn(run func(uint) error) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendStatusUpdateNotification provides a mock function with given fields: caseID, oldStatus, newStatus
func (_m *MockCaseService) SendStatusUpdateNotification(caseID uint, oldStatus models.CaseStatus, newStatus models.CaseStatus) error {
	ret := _m.Called(caseID, oldStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for SendStatusUpdateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.CaseStatus, models.CaseStatus) error); ok {
		r0 = rf(caseID, oldStatus, newStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaseService_SendStatusUpdateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStatusUpdateNotification'
type MockCaseService_SendStatusUpdateNotification_Call struct {
	*mock.Call
}

// SendStatusUpdateNotification is a helper method to define mock.On call
//   - caseID uint
//   - oldStatus models.CaseStatus
//   - newStatus models.CaseStatus
func (_e *MockCaseService_Expecter) SendStatusUpdateNotification(caseID interface{}, oldStatus interface{}, newStatus interface{}) *MockCaseService_SendStatusUpdateNotification_Call {
	return &MockCaseService_SendStatusUpdateNotification_Call{Call: _e.mock.On("SendStatusUpdateNotification", caseID, oldStatus, newStatus)}
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) Run(run func(caseID uint, oldStatus models.CaseStatus, newStatus models.CaseStatus)) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(models.CaseStatus), args[2].(models.CaseStatus))
	})
	return _c
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) Return(_a0 error) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) RunAndReturn(run func(uint, models.CaseStatus, models.CaseStatus) error) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: caseModel
func (_m *MockCaseService) Update(caseModel *models.Case) error {
	ret := _m.Called(caseModel)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Case) error); ok {
		r0 = rf(caseModel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCaseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - caseModel *models.Case
func (_e *MockCaseService_Expecter) Update(caseModel interface{}) *MockCaseService_Update_Call {
	return &MockCaseService_Update_Call{Call: _e.mock.On("Update", caseModel)}
}

func (_c *MockCaseService_Update_Call) Run(run func(caseModel *models.Case)) *MockCaseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Case))
	})
	return _c
}

func (_c *MockCaseService_Update_Call) Return(_a0 error) *MockCaseService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_Update_Call) RunAndReturn(run func(*models.Case) error) *MockCaseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *MockCaseService) UpdateStatus(id uint, status models.CaseStatus) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.CaseStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaseService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCaseService_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id uint
//   - status models.CaseStatus
func (_e *MockCaseService_Expecter) UpdateStatus(id interface{}, status interface{}) *MockCaseService_UpdateStatus_Call {
	return &MockCaseService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status)}
}

func (_c *MockCaseService_UpdateStatus_Call) Run(run func(id uint, status models.CaseStatus)) *MockCaseService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(models.CaseStatus))
	})
	return _c
}

func (_c *MockCaseService_UpdateStatus_Call) Return(_a0 error) *MockCaseService_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaseService_UpdateStatus_Call) RunAndReturn(run func(uint, models.CaseStatus) error) *MockCaseService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCaseService creates a new instance of MockCaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaseService {
	mock := &MockCaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
