// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/portal-plugin-abuse/internal/types/service"
	"go.lumeweb.com/queryutil"
)

// NewMockCaseService creates a new instance of MockCaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaseService {
	mock := &MockCaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCaseService is an autogenerated mock type for the CaseService type
type MockCaseService struct {
	mock.Mock
}

type MockCaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaseService) EXPECT() *MockCaseService_Expecter {
	return &MockCaseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Create(caseData *models.Case) (*models.Case, error) {
	ret := _mock.Called(caseData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Case) (*models.Case, error)); ok {
		return returnFunc(caseData)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Case) *models.Case); ok {
		r0 = returnFunc(caseData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Case) error); ok {
		r1 = returnFunc(caseData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCaseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - caseData *models.Case
func (_e *MockCaseService_Expecter) Create(caseData interface{}) *MockCaseService_Create_Call {
	return &MockCaseService_Create_Call{Call: _e.mock.On("Create", caseData)}
}

func (_c *MockCaseService_Create_Call) Run(run func(caseData *models.Case)) *MockCaseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Case
		if args[0] != nil {
			arg0 = args[0].(*models.Case)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_Create_Call) Return(caseParam *models.Case, err error) *MockCaseService_Create_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockCaseService_Create_Call) RunAndReturn(run func(caseData *models.Case) (*models.Case, error)) *MockCaseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get24HourAnalytics provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Get24HourAnalytics() (*service.CaseAnalytics, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get24HourAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*service.CaseAnalytics, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *service.CaseAnalytics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_Get24HourAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get24HourAnalytics'
type MockCaseService_Get24HourAnalytics_Call struct {
	*mock.Call
}

// Get24HourAnalytics is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) Get24HourAnalytics() *MockCaseService_Get24HourAnalytics_Call {
	return &MockCaseService_Get24HourAnalytics_Call{Call: _e.mock.On("Get24HourAnalytics")}
}

func (_c *MockCaseService_Get24HourAnalytics_Call) Run(run func()) *MockCaseService_Get24HourAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_Get24HourAnalytics_Call) Return(caseAnalytics *service.CaseAnalytics, err error) *MockCaseService_Get24HourAnalytics_Call {
	_c.Call.Return(caseAnalytics, err)
	return _c
}

func (_c *MockCaseService_Get24HourAnalytics_Call) RunAndReturn(run func() (*service.CaseAnalytics, error)) *MockCaseService_Get24HourAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// Get30DayAnalytics provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Get30DayAnalytics() (*service.CaseAnalytics, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get30DayAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*service.CaseAnalytics, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *service.CaseAnalytics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_Get30DayAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get30DayAnalytics'
type MockCaseService_Get30DayAnalytics_Call struct {
	*mock.Call
}

// Get30DayAnalytics is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) Get30DayAnalytics() *MockCaseService_Get30DayAnalytics_Call {
	return &MockCaseService_Get30DayAnalytics_Call{Call: _e.mock.On("Get30DayAnalytics")}
}

func (_c *MockCaseService_Get30DayAnalytics_Call) Run(run func()) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_Get30DayAnalytics_Call) Return(caseAnalytics *service.CaseAnalytics, err error) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Return(caseAnalytics, err)
	return _c
}

func (_c *MockCaseService_Get30DayAnalytics_Call) RunAndReturn(run func() (*service.CaseAnalytics, error)) *MockCaseService_Get30DayAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// Get7DayAnalytics provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Get7DayAnalytics() (*service.CaseAnalytics, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get7DayAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*service.CaseAnalytics, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *service.CaseAnalytics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_Get7DayAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get7DayAnalytics'
type MockCaseService_Get7DayAnalytics_Call struct {
	*mock.Call
}

// Get7DayAnalytics is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) Get7DayAnalytics() *MockCaseService_Get7DayAnalytics_Call {
	return &MockCaseService_Get7DayAnalytics_Call{Call: _e.mock.On("Get7DayAnalytics")}
}

func (_c *MockCaseService_Get7DayAnalytics_Call) Run(run func()) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_Get7DayAnalytics_Call) Return(caseAnalytics *service.CaseAnalytics, err error) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Return(caseAnalytics, err)
	return _c
}

func (_c *MockCaseService_Get7DayAnalytics_Call) RunAndReturn(run func() (*service.CaseAnalytics, error)) *MockCaseService_Get7DayAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnalytics provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetAnalytics(filters []queryutil.CrudFilter) (*service.CaseAnalytics, error) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 *service.CaseAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) (*service.CaseAnalytics, error)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) *service.CaseAnalytics); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CaseAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter) error); ok {
		r1 = returnFunc(filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalytics'
type MockCaseService_GetAnalytics_Call struct {
	*mock.Call
}

// GetAnalytics is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
func (_e *MockCaseService_Expecter) GetAnalytics(filters interface{}) *MockCaseService_GetAnalytics_Call {
	return &MockCaseService_GetAnalytics_Call{Call: _e.mock.On("GetAnalytics", filters)}
}

func (_c *MockCaseService_GetAnalytics_Call) Run(run func(filters []queryutil.CrudFilter)) *MockCaseService_GetAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_GetAnalytics_Call) Return(caseAnalytics *service.CaseAnalytics, err error) *MockCaseService_GetAnalytics_Call {
	_c.Call.Return(caseAnalytics, err)
	return _c
}

func (_c *MockCaseService_GetAnalytics_Call) RunAndReturn(run func(filters []queryutil.CrudFilter) (*service.CaseAnalytics, error)) *MockCaseService_GetAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetByID(id uint) (*models.Case, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.Case, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.Case); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCaseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCaseService_Expecter) GetByID(id interface{}) *MockCaseService_GetByID_Call {
	return &MockCaseService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCaseService_GetByID_Call) Run(run func(id uint)) *MockCaseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_GetByID_Call) Return(caseParam *models.Case, err error) *MockCaseService_GetByID_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockCaseService_GetByID_Call) RunAndReturn(run func(id uint) (*models.Case, error)) *MockCaseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCaseByReference provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetCaseByReference(reference string) (*models.Case, error) {
	ret := _mock.Called(reference)

	if len(ret) == 0 {
		panic("no return value specified for GetCaseByReference")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Case, error)); ok {
		return returnFunc(reference)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Case); ok {
		r0 = returnFunc(reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetCaseByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCaseByReference'
type MockCaseService_GetCaseByReference_Call struct {
	*mock.Call
}

// GetCaseByReference is a helper method to define mock.On call
//   - reference string
func (_e *MockCaseService_Expecter) GetCaseByReference(reference interface{}) *MockCaseService_GetCaseByReference_Call {
	return &MockCaseService_GetCaseByReference_Call{Call: _e.mock.On("GetCaseByReference", reference)}
}

func (_c *MockCaseService_GetCaseByReference_Call) Run(run func(reference string)) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_GetCaseByReference_Call) Return(caseParam *models.Case, err error) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockCaseService_GetCaseByReference_Call) RunAndReturn(run func(reference string) (*models.Case, error)) *MockCaseService_GetCaseByReference_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicCase provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetPublicCase(reference string, reporterID uint) (*models.Case, error) {
	ret := _mock.Called(reference, reporterID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCase")
	}

	var r0 *models.Case
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) (*models.Case, error)); ok {
		return returnFunc(reference, reporterID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint) *models.Case); ok {
		r0 = returnFunc(reference, reporterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = returnFunc(reference, reporterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetPublicCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicCase'
type MockCaseService_GetPublicCase_Call struct {
	*mock.Call
}

// GetPublicCase is a helper method to define mock.On call
//   - reference string
//   - reporterID uint
func (_e *MockCaseService_Expecter) GetPublicCase(reference interface{}, reporterID interface{}) *MockCaseService_GetPublicCase_Call {
	return &MockCaseService_GetPublicCase_Call{Call: _e.mock.On("GetPublicCase", reference, reporterID)}
}

func (_c *MockCaseService_GetPublicCase_Call) Run(run func(reference string, reporterID uint)) *MockCaseService_GetPublicCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaseService_GetPublicCase_Call) Return(caseParam *models.Case, err error) *MockCaseService_GetPublicCase_Call {
	_c.Call.Return(caseParam, err)
	return _c
}

func (_c *MockCaseService_GetPublicCase_Call) RunAndReturn(run func(reference string, reporterID uint) (*models.Case, error)) *MockCaseService_GetPublicCase_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusFlowData provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetStatusFlowData(filters []queryutil.CrudFilter) (*service.StatusFlowGraph, error) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusFlowData")
	}

	var r0 *service.StatusFlowGraph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) (*service.StatusFlowGraph, error)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter) *service.StatusFlowGraph); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StatusFlowGraph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter) error); ok {
		r1 = returnFunc(filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetStatusFlowData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusFlowData'
type MockCaseService_GetStatusFlowData_Call struct {
	*mock.Call
}

// GetStatusFlowData is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
func (_e *MockCaseService_Expecter) GetStatusFlowData(filters interface{}) *MockCaseService_GetStatusFlowData_Call {
	return &MockCaseService_GetStatusFlowData_Call{Call: _e.mock.On("GetStatusFlowData", filters)}
}

func (_c *MockCaseService_GetStatusFlowData_Call) Run(run func(filters []queryutil.CrudFilter)) *MockCaseService_GetStatusFlowData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_GetStatusFlowData_Call) Return(statusFlowGraph *service.StatusFlowGraph, err error) *MockCaseService_GetStatusFlowData_Call {
	_c.Call.Return(statusFlowGraph, err)
	return _c
}

func (_c *MockCaseService_GetStatusFlowData_Call) RunAndReturn(run func(filters []queryutil.CrudFilter) (*service.StatusFlowGraph, error)) *MockCaseService_GetStatusFlowData_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeSeriesMetrics provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetTimeSeriesMetrics(metric string, timeRange string, filters []queryutil.CrudFilter) ([]int64, error) {
	ret := _mock.Called(metric, timeRange, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeSeriesMetrics")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []queryutil.CrudFilter) ([]int64, error)); ok {
		return returnFunc(metric, timeRange, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []queryutil.CrudFilter) []int64); ok {
		r0 = returnFunc(metric, timeRange, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []queryutil.CrudFilter) error); ok {
		r1 = returnFunc(metric, timeRange, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetTimeSeriesMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeSeriesMetrics'
type MockCaseService_GetTimeSeriesMetrics_Call struct {
	*mock.Call
}

// GetTimeSeriesMetrics is a helper method to define mock.On call
//   - metric string
//   - timeRange string
//   - filters []queryutil.CrudFilter
func (_e *MockCaseService_Expecter) GetTimeSeriesMetrics(metric interface{}, timeRange interface{}, filters interface{}) *MockCaseService_GetTimeSeriesMetrics_Call {
	return &MockCaseService_GetTimeSeriesMetrics_Call{Call: _e.mock.On("GetTimeSeriesMetrics", metric, timeRange, filters)}
}

func (_c *MockCaseService_GetTimeSeriesMetrics_Call) Run(run func(metric string, timeRange string, filters []queryutil.CrudFilter)) *MockCaseService_GetTimeSeriesMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCaseService_GetTimeSeriesMetrics_Call) Return(int64s []int64, err error) *MockCaseService_GetTimeSeriesMetrics_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockCaseService_GetTimeSeriesMetrics_Call) RunAndReturn(run func(metric string, timeRange string, filters []queryutil.CrudFilter) ([]int64, error)) *MockCaseService_GetTimeSeriesMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTypeSourceMatrix provides a mock function for the type MockCaseService
func (_mock *MockCaseService) GetTypeSourceMatrix(timeRange string, filters []queryutil.CrudFilter) ([]models.CaseTypeSourceBreakdown, error) {
	ret := _mock.Called(timeRange, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetTypeSourceMatrix")
	}

	var r0 []models.CaseTypeSourceBreakdown
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []queryutil.CrudFilter) ([]models.CaseTypeSourceBreakdown, error)); ok {
		return returnFunc(timeRange, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []queryutil.CrudFilter) []models.CaseTypeSourceBreakdown); ok {
		r0 = returnFunc(timeRange, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CaseTypeSourceBreakdown)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []queryutil.CrudFilter) error); ok {
		r1 = returnFunc(timeRange, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCaseService_GetTypeSourceMatrix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypeSourceMatrix'
type MockCaseService_GetTypeSourceMatrix_Call struct {
	*mock.Call
}

// GetTypeSourceMatrix is a helper method to define mock.On call
//   - timeRange string
//   - filters []queryutil.CrudFilter
func (_e *MockCaseService_Expecter) GetTypeSourceMatrix(timeRange interface{}, filters interface{}) *MockCaseService_GetTypeSourceMatrix_Call {
	return &MockCaseService_GetTypeSourceMatrix_Call{Call: _e.mock.On("GetTypeSourceMatrix", timeRange, filters)}
}

func (_c *MockCaseService_GetTypeSourceMatrix_Call) Run(run func(timeRange string, filters []queryutil.CrudFilter)) *MockCaseService_GetTypeSourceMatrix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaseService_GetTypeSourceMatrix_Call) Return(caseTypeSourceBreakdowns []models.CaseTypeSourceBreakdown, err error) *MockCaseService_GetTypeSourceMatrix_Call {
	_c.Call.Return(caseTypeSourceBreakdowns, err)
	return _c
}

func (_c *MockCaseService_GetTypeSourceMatrix_Call) RunAndReturn(run func(timeRange string, filters []queryutil.CrudFilter) ([]models.CaseTypeSourceBreakdown, error)) *MockCaseService_GetTypeSourceMatrix_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCaseService
func (_mock *MockCaseService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCaseService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCaseService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCaseService_Expecter) ID() *MockCaseService_ID_Call {
	return &MockCaseService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCaseService_ID_Call) Run(run func()) *MockCaseService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaseService_ID_Call) Return(s string) *MockCaseService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCaseService_ID_Call) RunAndReturn(run func() string) *MockCaseService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCaseService
func (_mock *MockCaseService) List(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Case, int64, error) {
	ret := _mock.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Case
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models.Case, int64, error)); ok {
		return returnFunc(filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models.Case); ok {
		r0 = returnFunc(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCaseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCaseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockCaseService_Expecter) List(filters interface{}, sorts interface{}, pagination interface{}) *MockCaseService_List_Call {
	return &MockCaseService_List_Call{Call: _e.mock.On("List", filters, sorts, pagination)}
}

func (_c *MockCaseService_List_Call) Run(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockCaseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		var arg1 []queryutil.Sort
		if args[1] != nil {
			arg1 = args[1].([]queryutil.Sort)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCaseService_List_Call) Return(cases []models.Case, n int64, err error) *MockCaseService_List_Call {
	_c.Call.Return(cases, n, err)
	return _c
}

func (_c *MockCaseService_List_Call) RunAndReturn(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Case, int64, error)) *MockCaseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Search(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Case, int64, error) {
	ret := _mock.Called(ctx, query, filters, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []models.Case
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) ([]models.Case, int64, error)); ok {
		return returnFunc(ctx, query, filters, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) []models.Case); ok {
		r0 = returnFunc(ctx, query, filters, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, query, filters, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, query, filters, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCaseService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCaseService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters []queryutil.CrudFilter
//   - pagination queryutil.Pagination
func (_e *MockCaseService_Expecter) Search(ctx interface{}, query interface{}, filters interface{}, pagination interface{}) *MockCaseService_Search_Call {
	return &MockCaseService_Search_Call{Call: _e.mock.On("Search", ctx, query, filters, pagination)}
}

func (_c *MockCaseService_Search_Call) Run(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination)) *MockCaseService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCaseService_Search_Call) Return(cases []models.Case, n int64, err error) *MockCaseService_Search_Call {
	_c.Call.Return(cases, n, err)
	return _c
}

func (_c *MockCaseService_Search_Call) RunAndReturn(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Case, int64, error)) *MockCaseService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SendCreationNotification provides a mock function for the type MockCaseService
func (_mock *MockCaseService) SendCreationNotification(caseID uint) error {
	ret := _mock.Called(caseID)

	if len(ret) == 0 {
		panic("no return value specified for SendCreationNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(caseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCaseService_SendCreationNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCreationNotification'
type MockCaseService_SendCreationNotification_Call struct {
	*mock.Call
}

// SendCreationNotification is a helper method to define mock.On call
//   - caseID uint
func (_e *MockCaseService_Expecter) SendCreationNotification(caseID interface{}) *MockCaseService_SendCreationNotification_Call {
	return &MockCaseService_SendCreationNotification_Call{Call: _e.mock.On("SendCreationNotification", caseID)}
}

func (_c *MockCaseService_SendCreationNotification_Call) Run(run func(caseID uint)) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_SendCreationNotification_Call) Return(err error) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCaseService_SendCreationNotification_Call) RunAndReturn(run func(caseID uint) error) *MockCaseService_SendCreationNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendStatusUpdateNotification provides a mock function for the type MockCaseService
func (_mock *MockCaseService) SendStatusUpdateNotification(caseID uint, oldStatus models.CaseStatus, newStatus models.CaseStatus) error {
	ret := _mock.Called(caseID, oldStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for SendStatusUpdateNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, models.CaseStatus, models.CaseStatus) error); ok {
		r0 = returnFunc(caseID, oldStatus, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCaseService_SendStatusUpdateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStatusUpdateNotification'
type MockCaseService_SendStatusUpdateNotification_Call struct {
	*mock.Call
}

// SendStatusUpdateNotification is a helper method to define mock.On call
//   - caseID uint
//   - oldStatus models.CaseStatus
//   - newStatus models.CaseStatus
func (_e *MockCaseService_Expecter) SendStatusUpdateNotification(caseID interface{}, oldStatus interface{}, newStatus interface{}) *MockCaseService_SendStatusUpdateNotification_Call {
	return &MockCaseService_SendStatusUpdateNotification_Call{Call: _e.mock.On("SendStatusUpdateNotification", caseID, oldStatus, newStatus)}
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) Run(run func(caseID uint, oldStatus models.CaseStatus, newStatus models.CaseStatus)) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 models.CaseStatus
		if args[1] != nil {
			arg1 = args[1].(models.CaseStatus)
		}
		var arg2 models.CaseStatus
		if args[2] != nil {
			arg2 = args[2].(models.CaseStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) Return(err error) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCaseService_SendStatusUpdateNotification_Call) RunAndReturn(run func(caseID uint, oldStatus models.CaseStatus, newStatus models.CaseStatus) error) *MockCaseService_SendStatusUpdateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCaseService
func (_mock *MockCaseService) Update(caseModel *models.Case) error {
	ret := _mock.Called(caseModel)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Case) error); ok {
		r0 = returnFunc(caseModel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCaseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCaseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - caseModel *models.Case
func (_e *MockCaseService_Expecter) Update(caseModel interface{}) *MockCaseService_Update_Call {
	return &MockCaseService_Update_Call{Call: _e.mock.On("Update", caseModel)}
}

func (_c *MockCaseService_Update_Call) Run(run func(caseModel *models.Case)) *MockCaseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Case
		if args[0] != nil {
			arg0 = args[0].(*models.Case)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCaseService_Update_Call) Return(err error) *MockCaseService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCaseService_Update_Call) RunAndReturn(run func(caseModel *models.Case) error) *MockCaseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockCaseService
func (_mock *MockCaseService) UpdateStatus(id uint, status models.CaseStatus) error {
	ret := _mock.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, models.CaseStatus) error); ok {
		r0 = returnFunc(id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCaseService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCaseService_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id uint
//   - status models.CaseStatus
func (_e *MockCaseService_Expecter) UpdateStatus(id interface{}, status interface{}) *MockCaseService_UpdateStatus_Call {
	return &MockCaseService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status)}
}

func (_c *MockCaseService_UpdateStatus_Call) Run(run func(id uint, status models.CaseStatus)) *MockCaseService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 models.CaseStatus
		if args[1] != nil {
			arg1 = args[1].(models.CaseStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaseService_UpdateStatus_Call) Return(err error) *MockCaseService_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCaseService_UpdateStatus_Call) RunAndReturn(run func(id uint, status models.CaseStatus) error) *MockCaseService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
