// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	queryutil "go.lumeweb.com/queryutil"

	service "go.lumeweb.com/portal-plugin-abuse/internal/types/service"

	time "time"
)

// MockCommunicationService is an autogenerated mock type for the CommunicationService type
type MockCommunicationService struct {
	mock.Mock
}

type MockCommunicationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommunicationService) EXPECT() *MockCommunicationService_Expecter {
	return &MockCommunicationService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: comm
func (_m *MockCommunicationService) Create(comm *models.Communication) (*models.Communication, error) {
	ret := _m.Called(comm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Communication
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Communication) (*models.Communication, error)); ok {
		return rf(comm)
	}
	if rf, ok := ret.Get(0).(func(*models.Communication) *models.Communication); ok {
		r0 = rf(comm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Communication) error); ok {
		r1 = rf(comm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunicationService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommunicationService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - comm *models.Communication
func (_e *MockCommunicationService_Expecter) Create(comm interface{}) *MockCommunicationService_Create_Call {
	return &MockCommunicationService_Create_Call{Call: _e.mock.On("Create", comm)}
}

func (_c *MockCommunicationService_Create_Call) Run(run func(comm *models.Communication)) *MockCommunicationService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Communication))
	})
	return _c
}

func (_c *MockCommunicationService_Create_Call) Return(_a0 *models.Communication, _a1 error) *MockCommunicationService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunicationService_Create_Call) RunAndReturn(run func(*models.Communication) (*models.Communication, error)) *MockCommunicationService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockCommunicationService) GetByID(id uint) (*models.Communication, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Communication
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Communication, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Communication); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunicationService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommunicationService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCommunicationService_Expecter) GetByID(id interface{}) *MockCommunicationService_GetByID_Call {
	return &MockCommunicationService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCommunicationService_GetByID_Call) Run(run func(id uint)) *MockCommunicationService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCommunicationService_GetByID_Call) Return(_a0 *models.Communication, _a1 error) *MockCommunicationService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunicationService_GetByID_Call) RunAndReturn(run func(uint) (*models.Communication, error)) *MockCommunicationService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByThreadID provides a mock function with given fields: threadID
func (_m *MockCommunicationService) GetByThreadID(threadID string) (*models.Communication, error) {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for GetByThreadID")
	}

	var r0 *models.Communication
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Communication, error)); ok {
		return rf(threadID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Communication); ok {
		r0 = rf(threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunicationService_GetByThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByThreadID'
type MockCommunicationService_GetByThreadID_Call struct {
	*mock.Call
}

// GetByThreadID is a helper method to define mock.On call
//   - threadID string
func (_e *MockCommunicationService_Expecter) GetByThreadID(threadID interface{}) *MockCommunicationService_GetByThreadID_Call {
	return &MockCommunicationService_GetByThreadID_Call{Call: _e.mock.On("GetByThreadID", threadID)}
}

func (_c *MockCommunicationService_GetByThreadID_Call) Run(run func(threadID string)) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommunicationService_GetByThreadID_Call) Return(_a0 *models.Communication, _a1 error) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunicationService_GetByThreadID_Call) RunAndReturn(run func(string) (*models.Communication, error)) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommunicationMetrics provides a mock function with given fields: start, end
func (_m *MockCommunicationService) GetCommunicationMetrics(start time.Time, end time.Time) (*service.CommAnalytics, error) {
	ret := _m.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationMetrics")
	}

	var r0 *service.CommAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) (*service.CommAnalytics, error)); ok {
		return rf(start, end)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) *service.CommAnalytics); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CommAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunicationService_GetCommunicationMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationMetrics'
type MockCommunicationService_GetCommunicationMetrics_Call struct {
	*mock.Call
}

// GetCommunicationMetrics is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockCommunicationService_Expecter) GetCommunicationMetrics(start interface{}, end interface{}) *MockCommunicationService_GetCommunicationMetrics_Call {
	return &MockCommunicationService_GetCommunicationMetrics_Call{Call: _e.mock.On("GetCommunicationMetrics", start, end)}
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) Run(run func(start time.Time, end time.Time)) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) Return(_a0 *service.CommAnalytics, _a1 error) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) RunAndReturn(run func(time.Time, time.Time) (*service.CommAnalytics, error)) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockCommunicationService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCommunicationService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCommunicationService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCommunicationService_Expecter) ID() *MockCommunicationService_ID_Call {
	return &MockCommunicationService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCommunicationService_ID_Call) Run(run func()) *MockCommunicationService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommunicationService_ID_Call) Return(_a0 string) *MockCommunicationService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunicationService_ID_Call) RunAndReturn(run func() string) *MockCommunicationService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCaseID provides a mock function with given fields: caseID, filters, sorts, pagination
func (_m *MockCommunicationService) ListByCaseID(caseID uint, filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Communication, int64, error) {
	ret := _m.Called(caseID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListByCaseID")
	}

	var r0 []models.Communication
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, []queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Communication, int64, error)); ok {
		return rf(caseID, filters, sorts, pagination)
	}
	if rf, ok := ret.Get(0).(func(uint, []queryutil.Filter, []queryutil.Sort, queryutil.Pagination) []models.Communication); ok {
		r0 = rf(caseID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Communication)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, []queryutil.Filter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = rf(caseID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, []queryutil.Filter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = rf(caseID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCommunicationService_ListByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCaseID'
type MockCommunicationService_ListByCaseID_Call struct {
	*mock.Call
}

// ListByCaseID is a helper method to define mock.On call
//   - caseID uint
//   - filters []queryutil.Filter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockCommunicationService_Expecter) ListByCaseID(caseID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockCommunicationService_ListByCaseID_Call {
	return &MockCommunicationService_ListByCaseID_Call{Call: _e.mock.On("ListByCaseID", caseID, filters, sorts, pagination)}
}

func (_c *MockCommunicationService_ListByCaseID_Call) Run(run func(caseID uint, filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].([]queryutil.Filter), args[2].([]queryutil.Sort), args[3].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockCommunicationService_ListByCaseID_Call) Return(_a0 []models.Communication, _a1 int64, _a2 error) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCommunicationService_ListByCaseID_Call) RunAndReturn(run func(uint, []queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Communication, int64, error)) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommunicationService creates a new instance of MockCommunicationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommunicationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommunicationService {
	mock := &MockCommunicationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
