// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/portal-plugin-abuse/internal/types/service"
	"go.lumeweb.com/queryutil"
)

// NewMockCommunicationService creates a new instance of MockCommunicationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommunicationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommunicationService {
	mock := &MockCommunicationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommunicationService is an autogenerated mock type for the CommunicationService type
type MockCommunicationService struct {
	mock.Mock
}

type MockCommunicationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommunicationService) EXPECT() *MockCommunicationService_Expecter {
	return &MockCommunicationService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) Create(comm *models.Communication) (*models.Communication, error) {
	ret := _mock.Called(comm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Communication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Communication) (*models.Communication, error)); ok {
		return returnFunc(comm)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Communication) *models.Communication); ok {
		r0 = returnFunc(comm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Communication) error); ok {
		r1 = returnFunc(comm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommunicationService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommunicationService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - comm *models.Communication
func (_e *MockCommunicationService_Expecter) Create(comm interface{}) *MockCommunicationService_Create_Call {
	return &MockCommunicationService_Create_Call{Call: _e.mock.On("Create", comm)}
}

func (_c *MockCommunicationService_Create_Call) Run(run func(comm *models.Communication)) *MockCommunicationService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Communication
		if args[0] != nil {
			arg0 = args[0].(*models.Communication)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommunicationService_Create_Call) Return(communication *models.Communication, err error) *MockCommunicationService_Create_Call {
	_c.Call.Return(communication, err)
	return _c
}

func (_c *MockCommunicationService_Create_Call) RunAndReturn(run func(comm *models.Communication) (*models.Communication, error)) *MockCommunicationService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) GetByID(id uint) (*models.Communication, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Communication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.Communication, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.Communication); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommunicationService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommunicationService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCommunicationService_Expecter) GetByID(id interface{}) *MockCommunicationService_GetByID_Call {
	return &MockCommunicationService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCommunicationService_GetByID_Call) Run(run func(id uint)) *MockCommunicationService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommunicationService_GetByID_Call) Return(communication *models.Communication, err error) *MockCommunicationService_GetByID_Call {
	_c.Call.Return(communication, err)
	return _c
}

func (_c *MockCommunicationService_GetByID_Call) RunAndReturn(run func(id uint) (*models.Communication, error)) *MockCommunicationService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByThreadID provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) GetByThreadID(threadID string) (*models.Communication, error) {
	ret := _mock.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for GetByThreadID")
	}

	var r0 *models.Communication
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Communication, error)); ok {
		return returnFunc(threadID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Communication); ok {
		r0 = returnFunc(threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Communication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(threadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommunicationService_GetByThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByThreadID'
type MockCommunicationService_GetByThreadID_Call struct {
	*mock.Call
}

// GetByThreadID is a helper method to define mock.On call
//   - threadID string
func (_e *MockCommunicationService_Expecter) GetByThreadID(threadID interface{}) *MockCommunicationService_GetByThreadID_Call {
	return &MockCommunicationService_GetByThreadID_Call{Call: _e.mock.On("GetByThreadID", threadID)}
}

func (_c *MockCommunicationService_GetByThreadID_Call) Run(run func(threadID string)) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommunicationService_GetByThreadID_Call) Return(communication *models.Communication, err error) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Return(communication, err)
	return _c
}

func (_c *MockCommunicationService_GetByThreadID_Call) RunAndReturn(run func(threadID string) (*models.Communication, error)) *MockCommunicationService_GetByThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommunicationMetrics provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) GetCommunicationMetrics(start time.Time, end time.Time) (*service.CommAnalytics, error) {
	ret := _mock.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationMetrics")
	}

	var r0 *service.CommAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time) (*service.CommAnalytics, error)); ok {
		return returnFunc(start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time) *service.CommAnalytics); ok {
		r0 = returnFunc(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CommAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = returnFunc(start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommunicationService_GetCommunicationMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationMetrics'
type MockCommunicationService_GetCommunicationMetrics_Call struct {
	*mock.Call
}

// GetCommunicationMetrics is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockCommunicationService_Expecter) GetCommunicationMetrics(start interface{}, end interface{}) *MockCommunicationService_GetCommunicationMetrics_Call {
	return &MockCommunicationService_GetCommunicationMetrics_Call{Call: _e.mock.On("GetCommunicationMetrics", start, end)}
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) Run(run func(start time.Time, end time.Time)) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) Return(commAnalytics *service.CommAnalytics, err error) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Return(commAnalytics, err)
	return _c
}

func (_c *MockCommunicationService_GetCommunicationMetrics_Call) RunAndReturn(run func(start time.Time, end time.Time) (*service.CommAnalytics, error)) *MockCommunicationService_GetCommunicationMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommunicationTimeline provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) GetCommunicationTimeline(timeRange string, filters []queryutil.CrudFilter) ([]models.CommunicationHourlyCount, error) {
	ret := _mock.Called(timeRange, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationTimeline")
	}

	var r0 []models.CommunicationHourlyCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []queryutil.CrudFilter) ([]models.CommunicationHourlyCount, error)); ok {
		return returnFunc(timeRange, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []queryutil.CrudFilter) []models.CommunicationHourlyCount); ok {
		r0 = returnFunc(timeRange, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CommunicationHourlyCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []queryutil.CrudFilter) error); ok {
		r1 = returnFunc(timeRange, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommunicationService_GetCommunicationTimeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationTimeline'
type MockCommunicationService_GetCommunicationTimeline_Call struct {
	*mock.Call
}

// GetCommunicationTimeline is a helper method to define mock.On call
//   - timeRange string
//   - filters []queryutil.CrudFilter
func (_e *MockCommunicationService_Expecter) GetCommunicationTimeline(timeRange interface{}, filters interface{}) *MockCommunicationService_GetCommunicationTimeline_Call {
	return &MockCommunicationService_GetCommunicationTimeline_Call{Call: _e.mock.On("GetCommunicationTimeline", timeRange, filters)}
}

func (_c *MockCommunicationService_GetCommunicationTimeline_Call) Run(run func(timeRange string, filters []queryutil.CrudFilter)) *MockCommunicationService_GetCommunicationTimeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommunicationService_GetCommunicationTimeline_Call) Return(communicationHourlyCounts []models.CommunicationHourlyCount, err error) *MockCommunicationService_GetCommunicationTimeline_Call {
	_c.Call.Return(communicationHourlyCounts, err)
	return _c
}

func (_c *MockCommunicationService_GetCommunicationTimeline_Call) RunAndReturn(run func(timeRange string, filters []queryutil.CrudFilter) ([]models.CommunicationHourlyCount, error)) *MockCommunicationService_GetCommunicationTimeline_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommunicationService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCommunicationService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCommunicationService_Expecter) ID() *MockCommunicationService_ID_Call {
	return &MockCommunicationService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCommunicationService_ID_Call) Run(run func()) *MockCommunicationService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommunicationService_ID_Call) Return(s string) *MockCommunicationService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommunicationService_ID_Call) RunAndReturn(run func() string) *MockCommunicationService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCaseID provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) ListByCaseID(caseID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Communication, int64, error) {
	ret := _mock.Called(caseID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListByCaseID")
	}

	var r0 []models.Communication
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models.Communication, int64, error)); ok {
		return returnFunc(caseID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models.Communication); ok {
		r0 = returnFunc(caseID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Communication)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(caseID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(caseID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCommunicationService_ListByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCaseID'
type MockCommunicationService_ListByCaseID_Call struct {
	*mock.Call
}

// ListByCaseID is a helper method to define mock.On call
//   - caseID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockCommunicationService_Expecter) ListByCaseID(caseID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockCommunicationService_ListByCaseID_Call {
	return &MockCommunicationService_ListByCaseID_Call{Call: _e.mock.On("ListByCaseID", caseID, filters, sorts, pagination)}
}

func (_c *MockCommunicationService_ListByCaseID_Call) Run(run func(caseID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []queryutil.Sort
		if args[2] != nil {
			arg2 = args[2].([]queryutil.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCommunicationService_ListByCaseID_Call) Return(communications []models.Communication, n int64, err error) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Return(communications, n, err)
	return _c
}

func (_c *MockCommunicationService_ListByCaseID_Call) RunAndReturn(run func(caseID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Communication, int64, error)) *MockCommunicationService_ListByCaseID_Call {
	_c.Call.Return(run)
	return _c
}
