// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	core "go.lumeweb.com/portal/core"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// GenerateCaseThreadID provides a mock function with given fields: caseID, referenceNumber
func (_m *MockEmailService) GenerateCaseThreadID(caseID uint, referenceNumber string) string {
	ret := _m.Called(caseID, referenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCaseThreadID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(uint, string) string); ok {
		r0 = rf(caseID, referenceNumber)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEmailService_GenerateCaseThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCaseThreadID'
type MockEmailService_GenerateCaseThreadID_Call struct {
	*mock.Call
}

// GenerateCaseThreadID is a helper method to define mock.On call
//   - caseID uint
//   - referenceNumber string
func (_e *MockEmailService_Expecter) GenerateCaseThreadID(caseID interface{}, referenceNumber interface{}) *MockEmailService_GenerateCaseThreadID_Call {
	return &MockEmailService_GenerateCaseThreadID_Call{Call: _e.mock.On("GenerateCaseThreadID", caseID, referenceNumber)}
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) Run(run func(caseID uint, referenceNumber string)) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) Return(_a0 string) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) RunAndReturn(run func(uint, string) string) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockEmailService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEmailService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEmailService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEmailService_Expecter) ID() *MockEmailService_ID_Call {
	return &MockEmailService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEmailService_ID_Call) Run(run func()) *MockEmailService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmailService_ID_Call) Return(_a0 string) *MockEmailService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_ID_Call) RunAndReturn(run func() string) *MockEmailService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessIncomingEmail provides a mock function with given fields: ctx, rawEmail
func (_m *MockEmailService) ProcessIncomingEmail(ctx context.Context, rawEmail io.Reader) error {
	ret := _m.Called(ctx, rawEmail)

	if len(ret) == 0 {
		panic("no return value specified for ProcessIncomingEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) error); ok {
		r0 = rf(ctx, rawEmail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_ProcessIncomingEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessIncomingEmail'
type MockEmailService_ProcessIncomingEmail_Call struct {
	*mock.Call
}

// ProcessIncomingEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - rawEmail io.Reader
func (_e *MockEmailService_Expecter) ProcessIncomingEmail(ctx interface{}, rawEmail interface{}) *MockEmailService_ProcessIncomingEmail_Call {
	return &MockEmailService_ProcessIncomingEmail_Call{Call: _e.mock.On("ProcessIncomingEmail", ctx, rawEmail)}
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) Run(run func(ctx context.Context, rawEmail io.Reader)) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) Return(_a0 error) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) RunAndReturn(run func(context.Context, io.Reader) error) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendTemplatedEmail provides a mock function with given fields: to, templateName, data
func (_m *MockEmailService) SendTemplatedEmail(to []string, templateName string, data core.MailerTemplateData) error {
	ret := _m.Called(to, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for SendTemplatedEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string, core.MailerTemplateData) error); ok {
		r0 = rf(to, templateName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_SendTemplatedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTemplatedEmail'
type MockEmailService_SendTemplatedEmail_Call struct {
	*mock.Call
}

// SendTemplatedEmail is a helper method to define mock.On call
//   - to []string
//   - templateName string
//   - data core.MailerTemplateData
func (_e *MockEmailService_Expecter) SendTemplatedEmail(to interface{}, templateName interface{}, data interface{}) *MockEmailService_SendTemplatedEmail_Call {
	return &MockEmailService_SendTemplatedEmail_Call{Call: _e.mock.On("SendTemplatedEmail", to, templateName, data)}
}

func (_c *MockEmailService_SendTemplatedEmail_Call) Run(run func(to []string, templateName string, data core.MailerTemplateData)) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(string), args[2].(core.MailerTemplateData))
	})
	return _c
}

func (_c *MockEmailService_SendTemplatedEmail_Call) Return(_a0 error) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_SendTemplatedEmail_Call) RunAndReturn(run func([]string, string, core.MailerTemplateData) error) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
