// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/mnako/letters"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockEmailService
func (_mock *MockEmailService) Config() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockEmailService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockEmailService_Expecter) Config() *MockEmailService_Config_Call {
	return &MockEmailService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockEmailService_Config_Call) Run(run func()) *MockEmailService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmailService_Config_Call) Return(v any, err error) *MockEmailService_Config_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockEmailService_Config_Call) RunAndReturn(run func() (any, error)) *MockEmailService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCaseThreadID provides a mock function for the type MockEmailService
func (_mock *MockEmailService) GenerateCaseThreadID(referenceNumber string) string {
	ret := _mock.Called(referenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCaseThreadID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(referenceNumber)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEmailService_GenerateCaseThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCaseThreadID'
type MockEmailService_GenerateCaseThreadID_Call struct {
	*mock.Call
}

// GenerateCaseThreadID is a helper method to define mock.On call
//   - referenceNumber string
func (_e *MockEmailService_Expecter) GenerateCaseThreadID(referenceNumber interface{}) *MockEmailService_GenerateCaseThreadID_Call {
	return &MockEmailService_GenerateCaseThreadID_Call{Call: _e.mock.On("GenerateCaseThreadID", referenceNumber)}
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) Run(run func(referenceNumber string)) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) Return(s string) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEmailService_GenerateCaseThreadID_Call) RunAndReturn(run func(referenceNumber string) string) *MockEmailService_GenerateCaseThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEmailService
func (_mock *MockEmailService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEmailService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEmailService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEmailService_Expecter) ID() *MockEmailService_ID_Call {
	return &MockEmailService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEmailService_ID_Call) Run(run func()) *MockEmailService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmailService_ID_Call) Return(s string) *MockEmailService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEmailService_ID_Call) RunAndReturn(run func() string) *MockEmailService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmailProcessed provides a mock function for the type MockEmailService
func (_mock *MockEmailService) IsEmailProcessed(email *letters.Email) (bool, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for IsEmailProcessed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*letters.Email) (bool, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(*letters.Email) bool); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*letters.Email) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailService_IsEmailProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmailProcessed'
type MockEmailService_IsEmailProcessed_Call struct {
	*mock.Call
}

// IsEmailProcessed is a helper method to define mock.On call
//   - email *letters.Email
func (_e *MockEmailService_Expecter) IsEmailProcessed(email interface{}) *MockEmailService_IsEmailProcessed_Call {
	return &MockEmailService_IsEmailProcessed_Call{Call: _e.mock.On("IsEmailProcessed", email)}
}

func (_c *MockEmailService_IsEmailProcessed_Call) Run(run func(email *letters.Email)) *MockEmailService_IsEmailProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *letters.Email
		if args[0] != nil {
			arg0 = args[0].(*letters.Email)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailService_IsEmailProcessed_Call) Return(b bool, err error) *MockEmailService_IsEmailProcessed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEmailService_IsEmailProcessed_Call) RunAndReturn(run func(email *letters.Email) (bool, error)) *MockEmailService_IsEmailProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailProcessed provides a mock function for the type MockEmailService
func (_mock *MockEmailService) MarkEmailProcessed(email *letters.Email) error {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*letters.Email) error); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_MarkEmailProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailProcessed'
type MockEmailService_MarkEmailProcessed_Call struct {
	*mock.Call
}

// MarkEmailProcessed is a helper method to define mock.On call
//   - email *letters.Email
func (_e *MockEmailService_Expecter) MarkEmailProcessed(email interface{}) *MockEmailService_MarkEmailProcessed_Call {
	return &MockEmailService_MarkEmailProcessed_Call{Call: _e.mock.On("MarkEmailProcessed", email)}
}

func (_c *MockEmailService_MarkEmailProcessed_Call) Run(run func(email *letters.Email)) *MockEmailService_MarkEmailProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *letters.Email
		if args[0] != nil {
			arg0 = args[0].(*letters.Email)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailService_MarkEmailProcessed_Call) Return(err error) *MockEmailService_MarkEmailProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_MarkEmailProcessed_Call) RunAndReturn(run func(email *letters.Email) error) *MockEmailService_MarkEmailProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessIncomingEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) ProcessIncomingEmail(ctx context.Context, rawEmail io.Reader) error {
	ret := _mock.Called(ctx, rawEmail)

	if len(ret) == 0 {
		panic("no return value specified for ProcessIncomingEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) error); ok {
		r0 = returnFunc(ctx, rawEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_ProcessIncomingEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessIncomingEmail'
type MockEmailService_ProcessIncomingEmail_Call struct {
	*mock.Call
}

// ProcessIncomingEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - rawEmail io.Reader
func (_e *MockEmailService_Expecter) ProcessIncomingEmail(ctx interface{}, rawEmail interface{}) *MockEmailService_ProcessIncomingEmail_Call {
	return &MockEmailService_ProcessIncomingEmail_Call{Call: _e.mock.On("ProcessIncomingEmail", ctx, rawEmail)}
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) Run(run func(ctx context.Context, rawEmail io.Reader)) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) Return(err error) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_ProcessIncomingEmail_Call) RunAndReturn(run func(ctx context.Context, rawEmail io.Reader) error) *MockEmailService_ProcessIncomingEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendTemplatedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendTemplatedEmail(to []string, templateName string, data core.MailerTemplateData) error {
	ret := _mock.Called(to, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for SendTemplatedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, string, core.MailerTemplateData) error); ok {
		r0 = returnFunc(to, templateName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendTemplatedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTemplatedEmail'
type MockEmailService_SendTemplatedEmail_Call struct {
	*mock.Call
}

// SendTemplatedEmail is a helper method to define mock.On call
//   - to []string
//   - templateName string
//   - data core.MailerTemplateData
func (_e *MockEmailService_Expecter) SendTemplatedEmail(to interface{}, templateName interface{}, data interface{}) *MockEmailService_SendTemplatedEmail_Call {
	return &MockEmailService_SendTemplatedEmail_Call{Call: _e.mock.On("SendTemplatedEmail", to, templateName, data)}
}

func (_c *MockEmailService_SendTemplatedEmail_Call) Run(run func(to []string, templateName string, data core.MailerTemplateData)) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 core.MailerTemplateData
		if args[2] != nil {
			arg2 = args[2].(core.MailerTemplateData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendTemplatedEmail_Call) Return(err error) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendTemplatedEmail_Call) RunAndReturn(run func(to []string, templateName string, data core.MailerTemplateData) error) *MockEmailService_SendTemplatedEmail_Call {
	_c.Call.Return(run)
	return _c
}
