// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	datatypes "gorm.io/datatypes"

	mock "github.com/stretchr/testify/mock"

	models "go.lumeweb.com/portal-plugin-abuse/internal/db/models"

	queryutil "go.lumeweb.com/queryutil"

	service "go.lumeweb.com/portal-plugin-abuse/internal/types/service"

	time "time"
)

// MockEvidenceService is an autogenerated mock type for the EvidenceService type
type MockEvidenceService struct {
	mock.Mock
}

type MockEvidenceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvidenceService) EXPECT() *MockEvidenceService_Expecter {
	return &MockEvidenceService_Expecter{mock: &_m.Mock}
}

// CreateFromData provides a mock function with given fields: r, model
func (_m *MockEvidenceService) CreateFromData(r io.ReadCloser, model *models.Evidence) (*models.Evidence, error) {
	ret := _m.Called(r, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromData")
	}

	var r0 *models.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(io.ReadCloser, *models.Evidence) (*models.Evidence, error)); ok {
		return rf(r, model)
	}
	if rf, ok := ret.Get(0).(func(io.ReadCloser, *models.Evidence) *models.Evidence); ok {
		r0 = rf(r, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(io.ReadCloser, *models.Evidence) error); ok {
		r1 = rf(r, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceService_CreateFromData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromData'
type MockEvidenceService_CreateFromData_Call struct {
	*mock.Call
}

// CreateFromData is a helper method to define mock.On call
//   - r io.ReadCloser
//   - model *models.Evidence
func (_e *MockEvidenceService_Expecter) CreateFromData(r interface{}, model interface{}) *MockEvidenceService_CreateFromData_Call {
	return &MockEvidenceService_CreateFromData_Call{Call: _e.mock.On("CreateFromData", r, model)}
}

func (_c *MockEvidenceService_CreateFromData_Call) Run(run func(r io.ReadCloser, model *models.Evidence)) *MockEvidenceService_CreateFromData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.ReadCloser), args[1].(*models.Evidence))
	})
	return _c
}

func (_c *MockEvidenceService_CreateFromData_Call) Return(_a0 *models.Evidence, _a1 error) *MockEvidenceService_CreateFromData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceService_CreateFromData_Call) RunAndReturn(run func(io.ReadCloser, *models.Evidence) (*models.Evidence, error)) *MockEvidenceService_CreateFromData_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromHash provides a mock function with given fields: caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata
func (_m *MockEvidenceService) CreateFromHash(caseID uint, submitterID uint, storageHash string, fileName string, contentType string, fileSize int64, source models.EvidenceSource, description string, metadata datatypes.JSON) (*models.Evidence, error) {
	ret := _m.Called(caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromHash")
	}

	var r0 *models.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, string, string, string, int64, models.EvidenceSource, string, datatypes.JSON) (*models.Evidence, error)); ok {
		return rf(caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, string, string, string, int64, models.EvidenceSource, string, datatypes.JSON) *models.Evidence); ok {
		r0 = rf(caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint, string, string, string, int64, models.EvidenceSource, string, datatypes.JSON) error); ok {
		r1 = rf(caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceService_CreateFromHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromHash'
type MockEvidenceService_CreateFromHash_Call struct {
	*mock.Call
}

// CreateFromHash is a helper method to define mock.On call
//   - caseID uint
//   - submitterID uint
//   - storageHash string
//   - fileName string
//   - contentType string
//   - fileSize int64
//   - source models.EvidenceSource
//   - description string
//   - metadata datatypes.JSON
func (_e *MockEvidenceService_Expecter) CreateFromHash(caseID interface{}, submitterID interface{}, storageHash interface{}, fileName interface{}, contentType interface{}, fileSize interface{}, source interface{}, description interface{}, metadata interface{}) *MockEvidenceService_CreateFromHash_Call {
	return &MockEvidenceService_CreateFromHash_Call{Call: _e.mock.On("CreateFromHash", caseID, submitterID, storageHash, fileName, contentType, fileSize, source, description, metadata)}
}

func (_c *MockEvidenceService_CreateFromHash_Call) Run(run func(caseID uint, submitterID uint, storageHash string, fileName string, contentType string, fileSize int64, source models.EvidenceSource, description string, metadata datatypes.JSON)) *MockEvidenceService_CreateFromHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint), args[2].(string), args[3].(string), args[4].(string), args[5].(int64), args[6].(models.EvidenceSource), args[7].(string), args[8].(datatypes.JSON))
	})
	return _c
}

func (_c *MockEvidenceService_CreateFromHash_Call) Return(_a0 *models.Evidence, _a1 error) *MockEvidenceService_CreateFromHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceService_CreateFromHash_Call) RunAndReturn(run func(uint, uint, string, string, string, int64, models.EvidenceSource, string, datatypes.JSON) (*models.Evidence, error)) *MockEvidenceService_CreateFromHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCaseID provides a mock function with given fields: caseID, pagination
func (_m *MockEvidenceService) GetByCaseID(caseID uint, pagination queryutil.Pagination) ([]models.Evidence, int64, error) {
	ret := _m.Called(caseID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetByCaseID")
	}

	var r0 []models.Evidence
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, queryutil.Pagination) ([]models.Evidence, int64, error)); ok {
		return rf(caseID, pagination)
	}
	if rf, ok := ret.Get(0).(func(uint, queryutil.Pagination) []models.Evidence); ok {
		r0 = rf(caseID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, queryutil.Pagination) int64); ok {
		r1 = rf(caseID, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, queryutil.Pagination) error); ok {
		r2 = rf(caseID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEvidenceService_GetByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCaseID'
type MockEvidenceService_GetByCaseID_Call struct {
	*mock.Call
}

// GetByCaseID is a helper method to define mock.On call
//   - caseID uint
//   - pagination queryutil.Pagination
func (_e *MockEvidenceService_Expecter) GetByCaseID(caseID interface{}, pagination interface{}) *MockEvidenceService_GetByCaseID_Call {
	return &MockEvidenceService_GetByCaseID_Call{Call: _e.mock.On("GetByCaseID", caseID, pagination)}
}

func (_c *MockEvidenceService_GetByCaseID_Call) Run(run func(caseID uint, pagination queryutil.Pagination)) *MockEvidenceService_GetByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockEvidenceService_GetByCaseID_Call) Return(_a0 []models.Evidence, _a1 int64, _a2 error) *MockEvidenceService_GetByCaseID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEvidenceService_GetByCaseID_Call) RunAndReturn(run func(uint, queryutil.Pagination) ([]models.Evidence, int64, error)) *MockEvidenceService_GetByCaseID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockEvidenceService) GetByID(id uint) (*models.Evidence, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Evidence, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Evidence); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEvidenceService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockEvidenceService_Expecter) GetByID(id interface{}) *MockEvidenceService_GetByID_Call {
	return &MockEvidenceService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockEvidenceService_GetByID_Call) Run(run func(id uint)) *MockEvidenceService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockEvidenceService_GetByID_Call) Return(_a0 *models.Evidence, _a1 error) *MockEvidenceService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceService_GetByID_Call) RunAndReturn(run func(uint) (*models.Evidence, error)) *MockEvidenceService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetContent provides a mock function with given fields: id
func (_m *MockEvidenceService) GetContent(id uint) (io.ReadCloser, string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetContent")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(uint) (io.ReadCloser, string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) io.ReadCloser); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) string); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(uint) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEvidenceService_GetContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContent'
type MockEvidenceService_GetContent_Call struct {
	*mock.Call
}

// GetContent is a helper method to define mock.On call
//   - id uint
func (_e *MockEvidenceService_Expecter) GetContent(id interface{}) *MockEvidenceService_GetContent_Call {
	return &MockEvidenceService_GetContent_Call{Call: _e.mock.On("GetContent", id)}
}

func (_c *MockEvidenceService_GetContent_Call) Run(run func(id uint)) *MockEvidenceService_GetContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockEvidenceService_GetContent_Call) Return(_a0 io.ReadCloser, _a1 string, _a2 error) *MockEvidenceService_GetContent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEvidenceService_GetContent_Call) RunAndReturn(run func(uint) (io.ReadCloser, string, error)) *MockEvidenceService_GetContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvidenceMetrics provides a mock function with given fields: start, end
func (_m *MockEvidenceService) GetEvidenceMetrics(start time.Time, end time.Time) (*service.EvidenceAnalytics, error) {
	ret := _m.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetEvidenceMetrics")
	}

	var r0 *service.EvidenceAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) (*service.EvidenceAnalytics, error)); ok {
		return rf(start, end)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) *service.EvidenceAnalytics); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EvidenceAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvidenceService_GetEvidenceMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvidenceMetrics'
type MockEvidenceService_GetEvidenceMetrics_Call struct {
	*mock.Call
}

// GetEvidenceMetrics is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockEvidenceService_Expecter) GetEvidenceMetrics(start interface{}, end interface{}) *MockEvidenceService_GetEvidenceMetrics_Call {
	return &MockEvidenceService_GetEvidenceMetrics_Call{Call: _e.mock.On("GetEvidenceMetrics", start, end)}
}

func (_c *MockEvidenceService_GetEvidenceMetrics_Call) Run(run func(start time.Time, end time.Time)) *MockEvidenceService_GetEvidenceMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockEvidenceService_GetEvidenceMetrics_Call) Return(_a0 *service.EvidenceAnalytics, _a1 error) *MockEvidenceService_GetEvidenceMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvidenceService_GetEvidenceMetrics_Call) RunAndReturn(run func(time.Time, time.Time) (*service.EvidenceAnalytics, error)) *MockEvidenceService_GetEvidenceMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockEvidenceService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEvidenceService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEvidenceService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEvidenceService_Expecter) ID() *MockEvidenceService_ID_Call {
	return &MockEvidenceService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEvidenceService_ID_Call) Run(run func()) *MockEvidenceService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvidenceService_ID_Call) Return(_a0 string) *MockEvidenceService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvidenceService_ID_Call) RunAndReturn(run func() string) *MockEvidenceService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvidenceService creates a new instance of MockEvidenceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvidenceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvidenceService {
	mock := &MockEvidenceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
