// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/queryutil"
)

// NewMockReporterService creates a new instance of MockReporterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporterService {
	mock := &MockReporterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReporterService is an autogenerated mock type for the ReporterService type
type MockReporterService struct {
	mock.Mock
}

type MockReporterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporterService) EXPECT() *MockReporterService_Expecter {
	return &MockReporterService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReporterService
func (_mock *MockReporterService) Create(reporter *models.Reporter) (*models.Reporter, error) {
	ret := _mock.Called(reporter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Reporter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Reporter) (*models.Reporter, error)); ok {
		return returnFunc(reporter)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Reporter) *models.Reporter); ok {
		r0 = returnFunc(reporter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Reporter) error); ok {
		r1 = returnFunc(reporter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReporterService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReporterService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - reporter *models.Reporter
func (_e *MockReporterService_Expecter) Create(reporter interface{}) *MockReporterService_Create_Call {
	return &MockReporterService_Create_Call{Call: _e.mock.On("Create", reporter)}
}

func (_c *MockReporterService_Create_Call) Run(run func(reporter *models.Reporter)) *MockReporterService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Reporter
		if args[0] != nil {
			arg0 = args[0].(*models.Reporter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporterService_Create_Call) Return(reporter1 *models.Reporter, err error) *MockReporterService_Create_Call {
	_c.Call.Return(reporter1, err)
	return _c
}

func (_c *MockReporterService_Create_Call) RunAndReturn(run func(reporter *models.Reporter) (*models.Reporter, error)) *MockReporterService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockReporterService
func (_mock *MockReporterService) GetByEmail(email string) (*models.Reporter, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.Reporter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Reporter, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Reporter); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReporterService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockReporterService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockReporterService_Expecter) GetByEmail(email interface{}) *MockReporterService_GetByEmail_Call {
	return &MockReporterService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockReporterService_GetByEmail_Call) Run(run func(email string)) *MockReporterService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporterService_GetByEmail_Call) Return(reporter *models.Reporter, err error) *MockReporterService_GetByEmail_Call {
	_c.Call.Return(reporter, err)
	return _c
}

func (_c *MockReporterService_GetByEmail_Call) RunAndReturn(run func(email string) (*models.Reporter, error)) *MockReporterService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockReporterService
func (_mock *MockReporterService) GetByID(id uint) (*models.Reporter, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Reporter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.Reporter, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.Reporter); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReporterService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReporterService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockReporterService_Expecter) GetByID(id interface{}) *MockReporterService_GetByID_Call {
	return &MockReporterService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockReporterService_GetByID_Call) Run(run func(id uint)) *MockReporterService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporterService_GetByID_Call) Return(reporter *models.Reporter, err error) *MockReporterService_GetByID_Call {
	_c.Call.Return(reporter, err)
	return _c
}

func (_c *MockReporterService_GetByID_Call) RunAndReturn(run func(id uint) (*models.Reporter, error)) *MockReporterService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockReporterService
func (_mock *MockReporterService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReporterService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockReporterService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockReporterService_Expecter) ID() *MockReporterService_ID_Call {
	return &MockReporterService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockReporterService_ID_Call) Run(run func()) *MockReporterService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReporterService_ID_Call) Return(s string) *MockReporterService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReporterService_ID_Call) RunAndReturn(run func() string) *MockReporterService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockReporterService
func (_mock *MockReporterService) List(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Reporter, int64, error) {
	ret := _mock.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Reporter
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models.Reporter, int64, error)); ok {
		return returnFunc(filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models.Reporter); ok {
		r0 = returnFunc(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReporterService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockReporterService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockReporterService_Expecter) List(filters interface{}, sorts interface{}, pagination interface{}) *MockReporterService_List_Call {
	return &MockReporterService_List_Call{Call: _e.mock.On("List", filters, sorts, pagination)}
}

func (_c *MockReporterService_List_Call) Run(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockReporterService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		var arg1 []queryutil.Sort
		if args[1] != nil {
			arg1 = args[1].([]queryutil.Sort)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReporterService_List_Call) Return(reporters []models.Reporter, n int64, err error) *MockReporterService_List_Call {
	_c.Call.Return(reporters, n, err)
	return _c
}

func (_c *MockReporterService_List_Call) RunAndReturn(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Reporter, int64, error)) *MockReporterService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReporterService
func (_mock *MockReporterService) Update(reporter *models.Reporter) error {
	ret := _mock.Called(reporter)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Reporter) error); ok {
		r0 = returnFunc(reporter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReporterService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReporterService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - reporter *models.Reporter
func (_e *MockReporterService_Expecter) Update(reporter interface{}) *MockReporterService_Update_Call {
	return &MockReporterService_Update_Call{Call: _e.mock.On("Update", reporter)}
}

func (_c *MockReporterService_Update_Call) Run(run func(reporter *models.Reporter)) *MockReporterService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Reporter
		if args[0] != nil {
			arg0 = args[0].(*models.Reporter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporterService_Update_Call) Return(err error) *MockReporterService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReporterService_Update_Call) RunAndReturn(run func(reporter *models.Reporter) error) *MockReporterService_Update_Call {
	_c.Call.Return(run)
	return _c
}
