// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	core "go.lumeweb.com/portal/core"

	models "go.lumeweb.com/portal-plugin-abuse/internal/db/models"

	queryutil "go.lumeweb.com/queryutil"
)

// MockScanService is an autogenerated mock type for the ScanService type
type MockScanService struct {
	mock.Mock
}

type MockScanService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanService) EXPECT() *MockScanService_Expecter {
	return &MockScanService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *MockScanService) Config() (any, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func() (any, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockScanService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockScanService_Expecter) Config() *MockScanService_Config_Call {
	return &MockScanService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockScanService_Config_Call) Run(run func()) *MockScanService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScanService_Config_Call) Return(_a0 any, _a1 error) *MockScanService_Config_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanService_Config_Call) RunAndReturn(run func() (any, error)) *MockScanService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// CreateScanRequest provides a mock function with given fields: caseID
func (_m *MockScanService) CreateScanRequest(caseID uint) error {
	ret := _m.Called(caseID)

	if len(ret) == 0 {
		panic("no return value specified for CreateScanRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(caseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanService_CreateScanRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScanRequest'
type MockScanService_CreateScanRequest_Call struct {
	*mock.Call
}

// CreateScanRequest is a helper method to define mock.On call
//   - caseID uint
func (_e *MockScanService_Expecter) CreateScanRequest(caseID interface{}) *MockScanService_CreateScanRequest_Call {
	return &MockScanService_CreateScanRequest_Call{Call: _e.mock.On("CreateScanRequest", caseID)}
}

func (_c *MockScanService_CreateScanRequest_Call) Run(run func(caseID uint)) *MockScanService_CreateScanRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockScanService_CreateScanRequest_Call) Return(_a0 error) *MockScanService_CreateScanRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanService_CreateScanRequest_Call) RunAndReturn(run func(uint) error) *MockScanService_CreateScanRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetScanById provides a mock function with given fields: scanID
func (_m *MockScanService) GetScanById(scanID uint) (*models.CaseScan, error) {
	ret := _m.Called(scanID)

	if len(ret) == 0 {
		panic("no return value specified for GetScanById")
	}

	var r0 *models.CaseScan
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.CaseScan, error)); ok {
		return rf(scanID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.CaseScan); ok {
		r0 = rf(scanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseScan)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(scanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanService_GetScanById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanById'
type MockScanService_GetScanById_Call struct {
	*mock.Call
}

// GetScanById is a helper method to define mock.On call
//   - scanID uint
func (_e *MockScanService_Expecter) GetScanById(scanID interface{}) *MockScanService_GetScanById_Call {
	return &MockScanService_GetScanById_Call{Call: _e.mock.On("GetScanById", scanID)}
}

func (_c *MockScanService_GetScanById_Call) Run(run func(scanID uint)) *MockScanService_GetScanById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockScanService_GetScanById_Call) Return(_a0 *models.CaseScan, _a1 error) *MockScanService_GetScanById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanService_GetScanById_Call) RunAndReturn(run func(uint) (*models.CaseScan, error)) *MockScanService_GetScanById_Call {
	_c.Call.Return(run)
	return _c
}

// GetScanResults provides a mock function with given fields: scanID
func (_m *MockScanService) GetScanResults(scanID uint) ([]*core.ScanResult, error) {
	ret := _m.Called(scanID)

	if len(ret) == 0 {
		panic("no return value specified for GetScanResults")
	}

	var r0 []*core.ScanResult
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*core.ScanResult, error)); ok {
		return rf(scanID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*core.ScanResult); ok {
		r0 = rf(scanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.ScanResult)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(scanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanService_GetScanResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanResults'
type MockScanService_GetScanResults_Call struct {
	*mock.Call
}

// GetScanResults is a helper method to define mock.On call
//   - scanID uint
func (_e *MockScanService_Expecter) GetScanResults(scanID interface{}) *MockScanService_GetScanResults_Call {
	return &MockScanService_GetScanResults_Call{Call: _e.mock.On("GetScanResults", scanID)}
}

func (_c *MockScanService_GetScanResults_Call) Run(run func(scanID uint)) *MockScanService_GetScanResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockScanService_GetScanResults_Call) Return(_a0 []*core.ScanResult, _a1 error) *MockScanService_GetScanResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanService_GetScanResults_Call) RunAndReturn(run func(uint) ([]*core.ScanResult, error)) *MockScanService_GetScanResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetScansForCase provides a mock function with given fields: caseID, pagination
func (_m *MockScanService) GetScansForCase(caseID uint, pagination queryutil.Pagination) ([]models.CaseScan, int64, error) {
	ret := _m.Called(caseID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetScansForCase")
	}

	var r0 []models.CaseScan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, queryutil.Pagination) ([]models.CaseScan, int64, error)); ok {
		return rf(caseID, pagination)
	}
	if rf, ok := ret.Get(0).(func(uint, queryutil.Pagination) []models.CaseScan); ok {
		r0 = rf(caseID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CaseScan)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, queryutil.Pagination) int64); ok {
		r1 = rf(caseID, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint, queryutil.Pagination) error); ok {
		r2 = rf(caseID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockScanService_GetScansForCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScansForCase'
type MockScanService_GetScansForCase_Call struct {
	*mock.Call
}

// GetScansForCase is a helper method to define mock.On call
//   - caseID uint
//   - pagination queryutil.Pagination
func (_e *MockScanService_Expecter) GetScansForCase(caseID interface{}, pagination interface{}) *MockScanService_GetScansForCase_Call {
	return &MockScanService_GetScansForCase_Call{Call: _e.mock.On("GetScansForCase", caseID, pagination)}
}

func (_c *MockScanService_GetScansForCase_Call) Run(run func(caseID uint, pagination queryutil.Pagination)) *MockScanService_GetScansForCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockScanService_GetScansForCase_Call) Return(_a0 []models.CaseScan, _a1 int64, _a2 error) *MockScanService_GetScansForCase_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockScanService_GetScansForCase_Call) RunAndReturn(run func(uint, queryutil.Pagination) ([]models.CaseScan, int64, error)) *MockScanService_GetScansForCase_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockScanService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockScanService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockScanService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockScanService_Expecter) ID() *MockScanService_ID_Call {
	return &MockScanService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockScanService_ID_Call) Run(run func()) *MockScanService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScanService_ID_Call) Return(_a0 string) *MockScanService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanService_ID_Call) RunAndReturn(run func() string) *MockScanService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveScanResults provides a mock function with given fields: scanID, results
func (_m *MockScanService) SaveScanResults(scanID uint, results []*core.ScanResult) error {
	ret := _m.Called(scanID, results)

	if len(ret) == 0 {
		panic("no return value specified for SaveScanResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []*core.ScanResult) error); ok {
		r0 = rf(scanID, results)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanService_SaveScanResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveScanResults'
type MockScanService_SaveScanResults_Call struct {
	*mock.Call
}

// SaveScanResults is a helper method to define mock.On call
//   - scanID uint
//   - results []*core.ScanResult
func (_e *MockScanService_Expecter) SaveScanResults(scanID interface{}, results interface{}) *MockScanService_SaveScanResults_Call {
	return &MockScanService_SaveScanResults_Call{Call: _e.mock.On("SaveScanResults", scanID, results)}
}

func (_c *MockScanService_SaveScanResults_Call) Run(run func(scanID uint, results []*core.ScanResult)) *MockScanService_SaveScanResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].([]*core.ScanResult))
	})
	return _c
}

func (_c *MockScanService_SaveScanResults_Call) Return(_a0 error) *MockScanService_SaveScanResults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanService_SaveScanResults_Call) RunAndReturn(run func(uint, []*core.ScanResult) error) *MockScanService_SaveScanResults_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScanStatus provides a mock function with given fields: scanID, status
func (_m *MockScanService) UpdateScanStatus(scanID uint, status models.ScanStatus) error {
	ret := _m.Called(scanID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScanStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.ScanStatus) error); ok {
		r0 = rf(scanID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanService_UpdateScanStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScanStatus'
type MockScanService_UpdateScanStatus_Call struct {
	*mock.Call
}

// UpdateScanStatus is a helper method to define mock.On call
//   - scanID uint
//   - status models.ScanStatus
func (_e *MockScanService_Expecter) UpdateScanStatus(scanID interface{}, status interface{}) *MockScanService_UpdateScanStatus_Call {
	return &MockScanService_UpdateScanStatus_Call{Call: _e.mock.On("UpdateScanStatus", scanID, status)}
}

func (_c *MockScanService_UpdateScanStatus_Call) Run(run func(scanID uint, status models.ScanStatus)) *MockScanService_UpdateScanStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(models.ScanStatus))
	})
	return _c
}

func (_c *MockScanService_UpdateScanStatus_Call) Return(_a0 error) *MockScanService_UpdateScanStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanService_UpdateScanStatus_Call) RunAndReturn(run func(uint, models.ScanStatus) error) *MockScanService_UpdateScanStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanService creates a new instance of MockScanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanService {
	mock := &MockScanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
