// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/portal-plugin-abuse/internal/types/service"
	"go.lumeweb.com/queryutil"
)

// NewMockSearchService creates a new instance of MockSearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchService {
	mock := &MockSearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchService is an autogenerated mock type for the SearchService type
type MockSearchService struct {
	mock.Mock
}

type MockSearchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchService) EXPECT() *MockSearchService_Expecter {
	return &MockSearchService_Expecter{mock: &_m.Mock}
}

// GlobalSearch provides a mock function for the type MockSearchService
func (_mock *MockSearchService) GlobalSearch(ctx context.Context, query string, pagination queryutil.Pagination) (*service.GlobalSearchResult, error) {
	ret := _mock.Called(ctx, query, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GlobalSearch")
	}

	var r0 *service.GlobalSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, queryutil.Pagination) (*service.GlobalSearchResult, error)); ok {
		return returnFunc(ctx, query, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, queryutil.Pagination) *service.GlobalSearchResult); ok {
		r0 = returnFunc(ctx, query, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.GlobalSearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, queryutil.Pagination) error); ok {
		r1 = returnFunc(ctx, query, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchService_GlobalSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GlobalSearch'
type MockSearchService_GlobalSearch_Call struct {
	*mock.Call
}

// GlobalSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - pagination queryutil.Pagination
func (_e *MockSearchService_Expecter) GlobalSearch(ctx interface{}, query interface{}, pagination interface{}) *MockSearchService_GlobalSearch_Call {
	return &MockSearchService_GlobalSearch_Call{Call: _e.mock.On("GlobalSearch", ctx, query, pagination)}
}

func (_c *MockSearchService_GlobalSearch_Call) Run(run func(ctx context.Context, query string, pagination queryutil.Pagination)) *MockSearchService_GlobalSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSearchService_GlobalSearch_Call) Return(globalSearchResult *service.GlobalSearchResult, err error) *MockSearchService_GlobalSearch_Call {
	_c.Call.Return(globalSearchResult, err)
	return _c
}

func (_c *MockSearchService_GlobalSearch_Call) RunAndReturn(run func(ctx context.Context, query string, pagination queryutil.Pagination) (*service.GlobalSearchResult, error)) *MockSearchService_GlobalSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockSearchService
func (_mock *MockSearchService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSearchService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockSearchService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockSearchService_Expecter) ID() *MockSearchService_ID_Call {
	return &MockSearchService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockSearchService_ID_Call) Run(run func()) *MockSearchService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSearchService_ID_Call) Return(s string) *MockSearchService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSearchService_ID_Call) RunAndReturn(run func() string) *MockSearchService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchCases provides a mock function for the type MockSearchService
func (_mock *MockSearchService) SearchCases(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Case, int64, error) {
	ret := _mock.Called(ctx, query, filters, pagination)

	if len(ret) == 0 {
		panic("no return value specified for SearchCases")
	}

	var r0 []models.Case
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) ([]models.Case, int64, error)); ok {
		return returnFunc(ctx, query, filters, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) []models.Case); ok {
		r0 = returnFunc(ctx, query, filters, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, query, filters, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, query, filters, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSearchService_SearchCases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchCases'
type MockSearchService_SearchCases_Call struct {
	*mock.Call
}

// SearchCases is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters []queryutil.CrudFilter
//   - pagination queryutil.Pagination
func (_e *MockSearchService_Expecter) SearchCases(ctx interface{}, query interface{}, filters interface{}, pagination interface{}) *MockSearchService_SearchCases_Call {
	return &MockSearchService_SearchCases_Call{Call: _e.mock.On("SearchCases", ctx, query, filters, pagination)}
}

func (_c *MockSearchService_SearchCases_Call) Run(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination)) *MockSearchService_SearchCases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSearchService_SearchCases_Call) Return(cases []models.Case, n int64, err error) *MockSearchService_SearchCases_Call {
	_c.Call.Return(cases, n, err)
	return _c
}

func (_c *MockSearchService_SearchCases_Call) RunAndReturn(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Case, int64, error)) *MockSearchService_SearchCases_Call {
	_c.Call.Return(run)
	return _c
}

// SearchReporters provides a mock function for the type MockSearchService
func (_mock *MockSearchService) SearchReporters(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Reporter, int64, error) {
	ret := _mock.Called(ctx, query, filters, pagination)

	if len(ret) == 0 {
		panic("no return value specified for SearchReporters")
	}

	var r0 []models.Reporter
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) ([]models.Reporter, int64, error)); ok {
		return returnFunc(ctx, query, filters, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) []models.Reporter); ok {
		r0 = returnFunc(ctx, query, filters, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, query, filters, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []queryutil.CrudFilter, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, query, filters, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSearchService_SearchReporters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchReporters'
type MockSearchService_SearchReporters_Call struct {
	*mock.Call
}

// SearchReporters is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - filters []queryutil.CrudFilter
//   - pagination queryutil.Pagination
func (_e *MockSearchService_Expecter) SearchReporters(ctx interface{}, query interface{}, filters interface{}, pagination interface{}) *MockSearchService_SearchReporters_Call {
	return &MockSearchService_SearchReporters_Call{Call: _e.mock.On("SearchReporters", ctx, query, filters, pagination)}
}

func (_c *MockSearchService_SearchReporters_Call) Run(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination)) *MockSearchService_SearchReporters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSearchService_SearchReporters_Call) Return(reporters []models.Reporter, n int64, err error) *MockSearchService_SearchReporters_Call {
	_c.Call.Return(reporters, n, err)
	return _c
}

func (_c *MockSearchService_SearchReporters_Call) RunAndReturn(run func(ctx context.Context, query string, filters []queryutil.CrudFilter, pagination queryutil.Pagination) ([]models.Reporter, int64, error)) *MockSearchService_SearchReporters_Call {
	_c.Call.Return(run)
	return _c
}
