// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
)

// NewMockSubjectService creates a new instance of MockSubjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubjectService {
	mock := &MockSubjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubjectService is an autogenerated mock type for the SubjectService type
type MockSubjectService struct {
	mock.Mock
}

type MockSubjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubjectService) EXPECT() *MockSubjectService_Expecter {
	return &MockSubjectService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) Create(subject *models.Subject) (*models.Subject, error) {
	ret := _mock.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Subject) (*models.Subject, error)); ok {
		return returnFunc(subject)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Subject) *models.Subject); ok {
		r0 = returnFunc(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Subject) error); ok {
		r1 = returnFunc(subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubjectService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubjectService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - subject *models.Subject
func (_e *MockSubjectService_Expecter) Create(subject interface{}) *MockSubjectService_Create_Call {
	return &MockSubjectService_Create_Call{Call: _e.mock.On("Create", subject)}
}

func (_c *MockSubjectService_Create_Call) Run(run func(subject *models.Subject)) *MockSubjectService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Subject
		if args[0] != nil {
			arg0 = args[0].(*models.Subject)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubjectService_Create_Call) Return(subject1 *models.Subject, err error) *MockSubjectService_Create_Call {
	_c.Call.Return(subject1, err)
	return _c
}

func (_c *MockSubjectService_Create_Call) RunAndReturn(run func(subject *models.Subject) (*models.Subject, error)) *MockSubjectService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) FindOrCreate(identifier core.StorageHash, subjectType models.SubjectType, url string) (*models.Subject, error) {
	ret := _mock.Called(identifier, subjectType, url)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash, models.SubjectType, string) (*models.Subject, error)); ok {
		return returnFunc(identifier, subjectType, url)
	}
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash, models.SubjectType, string) *models.Subject); ok {
		r0 = returnFunc(identifier, subjectType, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.StorageHash, models.SubjectType, string) error); ok {
		r1 = returnFunc(identifier, subjectType, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubjectService_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockSubjectService_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - identifier core.StorageHash
//   - subjectType models.SubjectType
//   - url string
func (_e *MockSubjectService_Expecter) FindOrCreate(identifier interface{}, subjectType interface{}, url interface{}) *MockSubjectService_FindOrCreate_Call {
	return &MockSubjectService_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", identifier, subjectType, url)}
}

func (_c *MockSubjectService_FindOrCreate_Call) Run(run func(identifier core.StorageHash, subjectType models.SubjectType, url string)) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		var arg1 models.SubjectType
		if args[1] != nil {
			arg1 = args[1].(models.SubjectType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubjectService_FindOrCreate_Call) Return(subject *models.Subject, err error) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Return(subject, err)
	return _c
}

func (_c *MockSubjectService_FindOrCreate_Call) RunAndReturn(run func(identifier core.StorageHash, subjectType models.SubjectType, url string) (*models.Subject, error)) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateByURL provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) FindOrCreateByURL(url string, subjectType models.SubjectType) (*models.Subject, error) {
	ret := _mock.Called(url, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateByURL")
	}

	var r0 *models.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, models.SubjectType) (*models.Subject, error)); ok {
		return returnFunc(url, subjectType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.SubjectType) *models.Subject); ok {
		r0 = returnFunc(url, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.SubjectType) error); ok {
		r1 = returnFunc(url, subjectType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubjectService_FindOrCreateByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateByURL'
type MockSubjectService_FindOrCreateByURL_Call struct {
	*mock.Call
}

// FindOrCreateByURL is a helper method to define mock.On call
//   - url string
//   - subjectType models.SubjectType
func (_e *MockSubjectService_Expecter) FindOrCreateByURL(url interface{}, subjectType interface{}) *MockSubjectService_FindOrCreateByURL_Call {
	return &MockSubjectService_FindOrCreateByURL_Call{Call: _e.mock.On("FindOrCreateByURL", url, subjectType)}
}

func (_c *MockSubjectService_FindOrCreateByURL_Call) Run(run func(url string, subjectType models.SubjectType)) *MockSubjectService_FindOrCreateByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.SubjectType
		if args[1] != nil {
			arg1 = args[1].(models.SubjectType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubjectService_FindOrCreateByURL_Call) Return(subject *models.Subject, err error) *MockSubjectService_FindOrCreateByURL_Call {
	_c.Call.Return(subject, err)
	return _c
}

func (_c *MockSubjectService_FindOrCreateByURL_Call) RunAndReturn(run func(url string, subjectType models.SubjectType) (*models.Subject, error)) *MockSubjectService_FindOrCreateByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) GetByID(id uint) (*models.Subject, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.Subject, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.Subject); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubjectService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubjectService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockSubjectService_Expecter) GetByID(id interface{}) *MockSubjectService_GetByID_Call {
	return &MockSubjectService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockSubjectService_GetByID_Call) Run(run func(id uint)) *MockSubjectService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubjectService_GetByID_Call) Return(subject *models.Subject, err error) *MockSubjectService_GetByID_Call {
	_c.Call.Return(subject, err)
	return _c
}

func (_c *MockSubjectService_GetByID_Call) RunAndReturn(run func(id uint) (*models.Subject, error)) *MockSubjectService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSubjectService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockSubjectService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockSubjectService_Expecter) ID() *MockSubjectService_ID_Call {
	return &MockSubjectService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockSubjectService_ID_Call) Run(run func()) *MockSubjectService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubjectService_ID_Call) Return(s string) *MockSubjectService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSubjectService_ID_Call) RunAndReturn(run func() string) *MockSubjectService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSubjectService
func (_mock *MockSubjectService) List(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Subject, int64, error) {
	ret := _mock.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Subject
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models.Subject, int64, error)); ok {
		return returnFunc(filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models.Subject); ok {
		r0 = returnFunc(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSubjectService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubjectService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockSubjectService_Expecter) List(filters interface{}, sorts interface{}, pagination interface{}) *MockSubjectService_List_Call {
	return &MockSubjectService_List_Call{Call: _e.mock.On("List", filters, sorts, pagination)}
}

func (_c *MockSubjectService_List_Call) Run(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockSubjectService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		var arg1 []queryutil.Sort
		if args[1] != nil {
			arg1 = args[1].([]queryutil.Sort)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubjectService_List_Call) Return(subjects []models.Subject, n int64, err error) *MockSubjectService_List_Call {
	_c.Call.Return(subjects, n, err)
	return _c
}

func (_c *MockSubjectService_List_Call) RunAndReturn(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Subject, int64, error)) *MockSubjectService_List_Call {
	_c.Call.Return(run)
	return _c
}
