// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "go.lumeweb.com/portal-plugin-abuse/internal/db/models"
	queryutil "go.lumeweb.com/queryutil"
)

// MockSubjectService is an autogenerated mock type for the SubjectService type
type MockSubjectService struct {
	mock.Mock
}

type MockSubjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubjectService) EXPECT() *MockSubjectService_Expecter {
	return &MockSubjectService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: subject
func (_m *MockSubjectService) Create(subject *models.Subject) (*models.Subject, error) {
	ret := _m.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Subject
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Subject) (*models.Subject, error)); ok {
		return rf(subject)
	}
	if rf, ok := ret.Get(0).(func(*models.Subject) *models.Subject); ok {
		r0 = rf(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Subject) error); ok {
		r1 = rf(subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubjectService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - subject *models.Subject
func (_e *MockSubjectService_Expecter) Create(subject interface{}) *MockSubjectService_Create_Call {
	return &MockSubjectService_Create_Call{Call: _e.mock.On("Create", subject)}
}

func (_c *MockSubjectService_Create_Call) Run(run func(subject *models.Subject)) *MockSubjectService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Subject))
	})
	return _c
}

func (_c *MockSubjectService_Create_Call) Return(_a0 *models.Subject, _a1 error) *MockSubjectService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_Create_Call) RunAndReturn(run func(*models.Subject) (*models.Subject, error)) *MockSubjectService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function with given fields: identifier, subjectType
func (_m *MockSubjectService) FindOrCreate(identifier string, subjectType models.SubjectType) (*models.Subject, error) {
	ret := _m.Called(identifier, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.Subject
	var r1 error
	if rf, ok := ret.Get(0).(func(string, models.SubjectType) (*models.Subject, error)); ok {
		return rf(identifier, subjectType)
	}
	if rf, ok := ret.Get(0).(func(string, models.SubjectType) *models.Subject); ok {
		r0 = rf(identifier, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}

	if rf, ok := ret.Get(1).(func(string, models.SubjectType) error); ok {
		r1 = rf(identifier, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockSubjectService_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - identifier string
//   - subjectType models.SubjectType
func (_e *MockSubjectService_Expecter) FindOrCreate(identifier interface{}, subjectType interface{}) *MockSubjectService_FindOrCreate_Call {
	return &MockSubjectService_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", identifier, subjectType)}
}

func (_c *MockSubjectService_FindOrCreate_Call) Run(run func(identifier string, subjectType models.SubjectType)) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.SubjectType))
	})
	return _c
}

func (_c *MockSubjectService_FindOrCreate_Call) Return(_a0 *models.Subject, _a1 error) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_FindOrCreate_Call) RunAndReturn(run func(string, models.SubjectType) (*models.Subject, error)) *MockSubjectService_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockSubjectService) GetByID(id uint) (*models.Subject, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Subject
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Subject, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Subject); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subject)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubjectService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockSubjectService_Expecter) GetByID(id interface{}) *MockSubjectService_GetByID_Call {
	return &MockSubjectService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockSubjectService_GetByID_Call) Run(run func(id uint)) *MockSubjectService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockSubjectService_GetByID_Call) Return(_a0 *models.Subject, _a1 error) *MockSubjectService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_GetByID_Call) RunAndReturn(run func(uint) (*models.Subject, error)) *MockSubjectService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockSubjectService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSubjectService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockSubjectService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockSubjectService_Expecter) ID() *MockSubjectService_ID_Call {
	return &MockSubjectService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockSubjectService_ID_Call) Run(run func()) *MockSubjectService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubjectService_ID_Call) Return(_a0 string) *MockSubjectService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectService_ID_Call) RunAndReturn(run func() string) *MockSubjectService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: filters, sorts, pagination
func (_m *MockSubjectService) List(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Subject, int64, error) {
	ret := _m.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Subject
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Subject, int64, error)); ok {
		return rf(filters, sorts, pagination)
	}
	if rf, ok := ret.Get(0).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) []models.Subject); ok {
		r0 = rf(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Subject)
		}
	}

	if rf, ok := ret.Get(1).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = rf(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = rf(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSubjectService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubjectService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filters []queryutil.Filter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockSubjectService_Expecter) List(filters interface{}, sorts interface{}, pagination interface{}) *MockSubjectService_List_Call {
	return &MockSubjectService_List_Call{Call: _e.mock.On("List", filters, sorts, pagination)}
}

func (_c *MockSubjectService_List_Call) Run(run func(filters []queryutil.Filter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockSubjectService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]queryutil.Filter), args[1].([]queryutil.Sort), args[2].(queryutil.Pagination))
	})
	return _c
}

func (_c *MockSubjectService_List_Call) Return(_a0 []models.Subject, _a1 int64, _a2 error) *MockSubjectService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSubjectService_List_Call) RunAndReturn(run func([]queryutil.Filter, []queryutil.Sort, queryutil.Pagination) ([]models.Subject, int64, error)) *MockSubjectService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubjectService creates a new instance of MockSubjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubjectService {
	mock := &MockSubjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
