// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: caseID, reporterID, validDays
func (_m *MockTokenService) GenerateToken(caseID uint, reporterID uint, validDays int) (string, error) {
	ret := _m.Called(caseID, reporterID, validDays)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, int) (string, error)); ok {
		return rf(caseID, reporterID, validDays)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, int) string); ok {
		r0 = rf(caseID, reporterID, validDays)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint, uint, int) error); ok {
		r1 = rf(caseID, reporterID, validDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - caseID uint
//   - reporterID uint
//   - validDays int
func (_e *MockTokenService_Expecter) GenerateToken(caseID interface{}, reporterID interface{}, validDays interface{}) *MockTokenService_GenerateToken_Call {
	return &MockTokenService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", caseID, reporterID, validDays)}
}

func (_c *MockTokenService_GenerateToken_Call) Run(run func(caseID uint, reporterID uint, validDays int)) *MockTokenService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint), args[2].(int))
	})
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) Return(_a0 string, _a1 error) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) RunAndReturn(run func(uint, uint, int) (string, error)) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenParts provides a mock function with given fields: token
func (_m *MockTokenService) GetTokenParts(token string) []string {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenParts")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockTokenService_GetTokenParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenParts'
type MockTokenService_GetTokenParts_Call struct {
	*mock.Call
}

// GetTokenParts is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) GetTokenParts(token interface{}) *MockTokenService_GetTokenParts_Call {
	return &MockTokenService_GetTokenParts_Call{Call: _e.mock.On("GetTokenParts", token)}
}

func (_c *MockTokenService_GetTokenParts_Call) Run(run func(token string)) *MockTokenService_GetTokenParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_GetTokenParts_Call) Return(_a0 []string) *MockTokenService_GetTokenParts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_GetTokenParts_Call) RunAndReturn(run func(string) []string) *MockTokenService_GetTokenParts_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockTokenService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTokenService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) ID() *MockTokenService_ID_Call {
	return &MockTokenService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTokenService_ID_Call) Run(run func()) *MockTokenService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_ID_Call) Return(_a0 string) *MockTokenService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_ID_Call) RunAndReturn(run func() string) *MockTokenService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockTokenService) ValidateToken(token string) (uint, uint, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 uint
	var r1 uint
	var r2 bool
	if rf, ok := ret.Get(0).(func(string) (uint, uint, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) uint); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(uint)
	}

	if rf, ok := ret.Get(2).(func(string) bool); ok {
		r2 = rf(token)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockTokenService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) ValidateToken(token interface{}) *MockTokenService_ValidateToken_Call {
	return &MockTokenService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockTokenService_ValidateToken_Call) Run(run func(token string)) *MockTokenService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) Return(caseID uint, reporterID uint, valid bool) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(caseID, reporterID, valid)
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) RunAndReturn(run func(string) (uint, uint, bool)) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
