// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateToken(caseID uint, reporterID uint, validDays int) (string, time.Time, error) {
	ret := _mock.Called(caseID, reporterID, validDays)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, int) (string, time.Time, error)); ok {
		return returnFunc(caseID, reporterID, validDays)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint, int) string); ok {
		r0 = returnFunc(caseID, reporterID, validDays)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint, int) time.Time); ok {
		r1 = returnFunc(caseID, reporterID, validDays)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(uint, uint, int) error); ok {
		r2 = returnFunc(caseID, reporterID, validDays)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - caseID uint
//   - reporterID uint
//   - validDays int
func (_e *MockTokenService_Expecter) GenerateToken(caseID interface{}, reporterID interface{}, validDays interface{}) *MockTokenService_GenerateToken_Call {
	return &MockTokenService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", caseID, reporterID, validDays)}
}

func (_c *MockTokenService_GenerateToken_Call) Run(run func(caseID uint, reporterID uint, validDays int)) *MockTokenService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) Return(s string, time1 time.Time, err error) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) RunAndReturn(run func(caseID uint, reporterID uint, validDays int) (string, time.Time, error)) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenParts provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetTokenParts(token string) []string {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenParts")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockTokenService_GetTokenParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenParts'
type MockTokenService_GetTokenParts_Call struct {
	*mock.Call
}

// GetTokenParts is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) GetTokenParts(token interface{}) *MockTokenService_GetTokenParts_Call {
	return &MockTokenService_GetTokenParts_Call{Call: _e.mock.On("GetTokenParts", token)}
}

func (_c *MockTokenService_GetTokenParts_Call) Run(run func(token string)) *MockTokenService_GetTokenParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GetTokenParts_Call) Return(strings []string) *MockTokenService_GetTokenParts_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockTokenService_GetTokenParts_Call) RunAndReturn(run func(token string) []string) *MockTokenService_GetTokenParts_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTokenService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) ID() *MockTokenService_ID_Call {
	return &MockTokenService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTokenService_ID_Call) Run(run func()) *MockTokenService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_ID_Call) Return(s string) *MockTokenService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_ID_Call) RunAndReturn(run func() string) *MockTokenService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ValidateToken(token string) (uint, uint, bool) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 uint
	var r1 uint
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(string) (uint, uint, bool)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uint); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(string) uint); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Get(1).(uint)
	}
	if returnFunc, ok := ret.Get(2).(func(string) bool); ok {
		r2 = returnFunc(token)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockTokenService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) ValidateToken(token interface{}) *MockTokenService_ValidateToken_Call {
	return &MockTokenService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockTokenService_ValidateToken_Call) Run(run func(token string)) *MockTokenService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) Return(caseID uint, reporterID uint, valid bool) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(caseID, reporterID, valid)
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) RunAndReturn(run func(token string) (uint, uint, bool)) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
