// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package email

import (
	"github.com/emersion/go-imap"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIMAPClientConn creates a new instance of MockIMAPClientConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMAPClientConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMAPClientConn {
	mock := &MockIMAPClientConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMAPClientConn is an autogenerated mock type for the IMAPClientConn type
type MockIMAPClientConn struct {
	mock.Mock
}

type MockIMAPClientConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMAPClientConn) EXPECT() *MockIMAPClientConn_Expecter {
	return &MockIMAPClientConn_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Fetch(seqSet *imap.SeqSet, items []imap.FetchItem, ch chan *imap.Message) error {
	ret := _mock.Called(seqSet, items, ch)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*imap.SeqSet, []imap.FetchItem, chan *imap.Message) error); ok {
		r0 = returnFunc(seqSet, items, ch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClientConn_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIMAPClientConn_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - seqSet *imap.SeqSet
//   - items []imap.FetchItem
//   - ch chan *imap.Message
func (_e *MockIMAPClientConn_Expecter) Fetch(seqSet interface{}, items interface{}, ch interface{}) *MockIMAPClientConn_Fetch_Call {
	return &MockIMAPClientConn_Fetch_Call{Call: _e.mock.On("Fetch", seqSet, items, ch)}
}

func (_c *MockIMAPClientConn_Fetch_Call) Run(run func(seqSet *imap.SeqSet, items []imap.FetchItem, ch chan *imap.Message)) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *imap.SeqSet
		if args[0] != nil {
			arg0 = args[0].(*imap.SeqSet)
		}
		var arg1 []imap.FetchItem
		if args[1] != nil {
			arg1 = args[1].([]imap.FetchItem)
		}
		var arg2 chan *imap.Message
		if args[2] != nil {
			arg2 = args[2].(chan *imap.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMAPClientConn_Fetch_Call) Return(err error) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClientConn_Fetch_Call) RunAndReturn(run func(seqSet *imap.SeqSet, items []imap.FetchItem, ch chan *imap.Message) error) *MockIMAPClientConn_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Login(username string, password string) error {
	ret := _mock.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClientConn_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIMAPClientConn_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockIMAPClientConn_Expecter) Login(username interface{}, password interface{}) *MockIMAPClientConn_Login_Call {
	return &MockIMAPClientConn_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockIMAPClientConn_Login_Call) Run(run func(username string, password string)) *MockIMAPClientConn_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMAPClientConn_Login_Call) Return(err error) *MockIMAPClientConn_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClientConn_Login_Call) RunAndReturn(run func(username string, password string) error) *MockIMAPClientConn_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Logout() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClientConn_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIMAPClientConn_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockIMAPClientConn_Expecter) Logout() *MockIMAPClientConn_Logout_Call {
	return &MockIMAPClientConn_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockIMAPClientConn_Logout_Call) Run(run func()) *MockIMAPClientConn_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMAPClientConn_Logout_Call) Return(err error) *MockIMAPClientConn_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClientConn_Logout_Call) RunAndReturn(run func() error) *MockIMAPClientConn_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Noop provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Noop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Noop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClientConn_Noop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Noop'
type MockIMAPClientConn_Noop_Call struct {
	*mock.Call
}

// Noop is a helper method to define mock.On call
func (_e *MockIMAPClientConn_Expecter) Noop() *MockIMAPClientConn_Noop_Call {
	return &MockIMAPClientConn_Noop_Call{Call: _e.mock.On("Noop")}
}

func (_c *MockIMAPClientConn_Noop_Call) Run(run func()) *MockIMAPClientConn_Noop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMAPClientConn_Noop_Call) Return(err error) *MockIMAPClientConn_Noop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClientConn_Noop_Call) RunAndReturn(run func() error) *MockIMAPClientConn_Noop_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Search(criteria *imap.SearchCriteria) ([]uint32, error) {
	ret := _mock.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*imap.SearchCriteria) ([]uint32, error)); ok {
		return returnFunc(criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(*imap.SearchCriteria) []uint32); ok {
		r0 = returnFunc(criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*imap.SearchCriteria) error); ok {
		r1 = returnFunc(criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMAPClientConn_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockIMAPClientConn_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - criteria *imap.SearchCriteria
func (_e *MockIMAPClientConn_Expecter) Search(criteria interface{}) *MockIMAPClientConn_Search_Call {
	return &MockIMAPClientConn_Search_Call{Call: _e.mock.On("Search", criteria)}
}

func (_c *MockIMAPClientConn_Search_Call) Run(run func(criteria *imap.SearchCriteria)) *MockIMAPClientConn_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *imap.SearchCriteria
		if args[0] != nil {
			arg0 = args[0].(*imap.SearchCriteria)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMAPClientConn_Search_Call) Return(uint32s []uint32, err error) *MockIMAPClientConn_Search_Call {
	_c.Call.Return(uint32s, err)
	return _c
}

func (_c *MockIMAPClientConn_Search_Call) RunAndReturn(run func(criteria *imap.SearchCriteria) ([]uint32, error)) *MockIMAPClientConn_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Select(mailbox string, readOnly bool) (*imap.MailboxStatus, error) {
	ret := _mock.Called(mailbox, readOnly)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 *imap.MailboxStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (*imap.MailboxStatus, error)); ok {
		return returnFunc(mailbox, readOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) *imap.MailboxStatus); ok {
		r0 = returnFunc(mailbox, readOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imap.MailboxStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(mailbox, readOnly)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMAPClientConn_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockIMAPClientConn_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - mailbox string
//   - readOnly bool
func (_e *MockIMAPClientConn_Expecter) Select(mailbox interface{}, readOnly interface{}) *MockIMAPClientConn_Select_Call {
	return &MockIMAPClientConn_Select_Call{Call: _e.mock.On("Select", mailbox, readOnly)}
}

func (_c *MockIMAPClientConn_Select_Call) Run(run func(mailbox string, readOnly bool)) *MockIMAPClientConn_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMAPClientConn_Select_Call) Return(mailboxStatus *imap.MailboxStatus, err error) *MockIMAPClientConn_Select_Call {
	_c.Call.Return(mailboxStatus, err)
	return _c
}

func (_c *MockIMAPClientConn_Select_Call) RunAndReturn(run func(mailbox string, readOnly bool) (*imap.MailboxStatus, error)) *MockIMAPClientConn_Select_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockIMAPClientConn
func (_mock *MockIMAPClientConn) Store(seqSet *imap.SeqSet, item imap.StoreItem, flags []interface{}, ch chan *imap.Message) error {
	ret := _mock.Called(seqSet, item, flags, ch)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*imap.SeqSet, imap.StoreItem, []interface{}, chan *imap.Message) error); ok {
		r0 = returnFunc(seqSet, item, flags, ch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClientConn_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIMAPClientConn_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - seqSet *imap.SeqSet
//   - item imap.StoreItem
//   - flags []interface{}
//   - ch chan *imap.Message
func (_e *MockIMAPClientConn_Expecter) Store(seqSet interface{}, item interface{}, flags interface{}, ch interface{}) *MockIMAPClientConn_Store_Call {
	return &MockIMAPClientConn_Store_Call{Call: _e.mock.On("Store", seqSet, item, flags, ch)}
}

func (_c *MockIMAPClientConn_Store_Call) Run(run func(seqSet *imap.SeqSet, item imap.StoreItem, flags []interface{}, ch chan *imap.Message)) *MockIMAPClientConn_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *imap.SeqSet
		if args[0] != nil {
			arg0 = args[0].(*imap.SeqSet)
		}
		var arg1 imap.StoreItem
		if args[1] != nil {
			arg1 = args[1].(imap.StoreItem)
		}
		var arg2 []interface{}
		if args[2] != nil {
			arg2 = args[2].([]interface{})
		}
		var arg3 chan *imap.Message
		if args[3] != nil {
			arg3 = args[3].(chan *imap.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIMAPClientConn_Store_Call) Return(err error) *MockIMAPClientConn_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClientConn_Store_Call) RunAndReturn(run func(seqSet *imap.SeqSet, item imap.StoreItem, flags []interface{}, ch chan *imap.Message) error) *MockIMAPClientConn_Store_Call {
	_c.Call.Return(run)
	return _c
}
