// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package email

import (
	"github.com/mnako/letters"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContentExtractor creates a new instance of MockContentExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentExtractor {
	mock := &MockContentExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentExtractor is an autogenerated mock type for the ContentExtractor type
type MockContentExtractor struct {
	mock.Mock
}

type MockContentExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentExtractor) EXPECT() *MockContentExtractor_Expecter {
	return &MockContentExtractor_Expecter{mock: &_m.Mock}
}

// ExtractHashes provides a mock function for the type MockContentExtractor
func (_mock *MockContentExtractor) ExtractHashes(email *letters.Email) []string {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ExtractHashes")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(*letters.Email) []string); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockContentExtractor_ExtractHashes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractHashes'
type MockContentExtractor_ExtractHashes_Call struct {
	*mock.Call
}

// ExtractHashes is a helper method to define mock.On call
//   - email *letters.Email
func (_e *MockContentExtractor_Expecter) ExtractHashes(email interface{}) *MockContentExtractor_ExtractHashes_Call {
	return &MockContentExtractor_ExtractHashes_Call{Call: _e.mock.On("ExtractHashes", email)}
}

func (_c *MockContentExtractor_ExtractHashes_Call) Run(run func(email *letters.Email)) *MockContentExtractor_ExtractHashes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *letters.Email
		if args[0] != nil {
			arg0 = args[0].(*letters.Email)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContentExtractor_ExtractHashes_Call) Return(strings []string) *MockContentExtractor_ExtractHashes_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockContentExtractor_ExtractHashes_Call) RunAndReturn(run func(email *letters.Email) []string) *MockContentExtractor_ExtractHashes_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractURLs provides a mock function for the type MockContentExtractor
func (_mock *MockContentExtractor) ExtractURLs(email *letters.Email) []string {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ExtractURLs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(*letters.Email) []string); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockContentExtractor_ExtractURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractURLs'
type MockContentExtractor_ExtractURLs_Call struct {
	*mock.Call
}

// ExtractURLs is a helper method to define mock.On call
//   - email *letters.Email
func (_e *MockContentExtractor_Expecter) ExtractURLs(email interface{}) *MockContentExtractor_ExtractURLs_Call {
	return &MockContentExtractor_ExtractURLs_Call{Call: _e.mock.On("ExtractURLs", email)}
}

func (_c *MockContentExtractor_ExtractURLs_Call) Run(run func(email *letters.Email)) *MockContentExtractor_ExtractURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *letters.Email
		if args[0] != nil {
			arg0 = args[0].(*letters.Email)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContentExtractor_ExtractURLs_Call) Return(strings []string) *MockContentExtractor_ExtractURLs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockContentExtractor_ExtractURLs_Call) RunAndReturn(run func(email *letters.Email) []string) *MockContentExtractor_ExtractURLs_Call {
	_c.Call.Return(run)
	return _c
}
