// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package email

import (
	"crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIMAPDialer creates a new instance of MockIMAPDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMAPDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMAPDialer {
	mock := &MockIMAPDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMAPDialer is an autogenerated mock type for the IMAPDialer type
type MockIMAPDialer struct {
	mock.Mock
}

type MockIMAPDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMAPDialer) EXPECT() *MockIMAPDialer_Expecter {
	return &MockIMAPDialer_Expecter{mock: &_m.Mock}
}

// DialTLS provides a mock function for the type MockIMAPDialer
func (_mock *MockIMAPDialer) DialTLS(addr string, tlsConfig *tls.Config) (IMAPClientConn, error) {
	ret := _mock.Called(addr, tlsConfig)

	if len(ret) == 0 {
		panic("no return value specified for DialTLS")
	}

	var r0 IMAPClientConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *tls.Config) (IMAPClientConn, error)); ok {
		return returnFunc(addr, tlsConfig)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *tls.Config) IMAPClientConn); ok {
		r0 = returnFunc(addr, tlsConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IMAPClientConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *tls.Config) error); ok {
		r1 = returnFunc(addr, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMAPDialer_DialTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialTLS'
type MockIMAPDialer_DialTLS_Call struct {
	*mock.Call
}

// DialTLS is a helper method to define mock.On call
//   - addr string
//   - tlsConfig *tls.Config
func (_e *MockIMAPDialer_Expecter) DialTLS(addr interface{}, tlsConfig interface{}) *MockIMAPDialer_DialTLS_Call {
	return &MockIMAPDialer_DialTLS_Call{Call: _e.mock.On("DialTLS", addr, tlsConfig)}
}

func (_c *MockIMAPDialer_DialTLS_Call) Run(run func(addr string, tlsConfig *tls.Config)) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *tls.Config
		if args[1] != nil {
			arg1 = args[1].(*tls.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMAPDialer_DialTLS_Call) Return(iMAPClientConn IMAPClientConn, err error) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Return(iMAPClientConn, err)
	return _c
}

func (_c *MockIMAPDialer_DialTLS_Call) RunAndReturn(run func(addr string, tlsConfig *tls.Config) (IMAPClientConn, error)) *MockIMAPDialer_DialTLS_Call {
	_c.Call.Return(run)
	return _c
}
