// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package email

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIMAPClient creates a new instance of MockIMAPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMAPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMAPClient {
	mock := &MockIMAPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMAPClient is an autogenerated mock type for the IMAPClient type
type MockIMAPClient struct {
	mock.Mock
}

type MockIMAPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMAPClient) EXPECT() *MockIMAPClient_Expecter {
	return &MockIMAPClient_Expecter{mock: &_m.Mock}
}

// SetEmailHandler provides a mock function for the type MockIMAPClient
func (_mock *MockIMAPClient) SetEmailHandler(handler EmailHandlerFunc) {
	_mock.Called(handler)
	return
}

// MockIMAPClient_SetEmailHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEmailHandler'
type MockIMAPClient_SetEmailHandler_Call struct {
	*mock.Call
}

// SetEmailHandler is a helper method to define mock.On call
//   - handler EmailHandlerFunc
func (_e *MockIMAPClient_Expecter) SetEmailHandler(handler interface{}) *MockIMAPClient_SetEmailHandler_Call {
	return &MockIMAPClient_SetEmailHandler_Call{Call: _e.mock.On("SetEmailHandler", handler)}
}

func (_c *MockIMAPClient_SetEmailHandler_Call) Run(run func(handler EmailHandlerFunc)) *MockIMAPClient_SetEmailHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 EmailHandlerFunc
		if args[0] != nil {
			arg0 = args[0].(EmailHandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMAPClient_SetEmailHandler_Call) Return() *MockIMAPClient_SetEmailHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIMAPClient_SetEmailHandler_Call) RunAndReturn(run func(handler EmailHandlerFunc)) *MockIMAPClient_SetEmailHandler_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockIMAPClient
func (_mock *MockIMAPClient) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIMAPClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockIMAPClient_Expecter) Start() *MockIMAPClient_Start_Call {
	return &MockIMAPClient_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockIMAPClient_Start_Call) Run(run func()) *MockIMAPClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMAPClient_Start_Call) Return(err error) *MockIMAPClient_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClient_Start_Call) RunAndReturn(run func() error) *MockIMAPClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockIMAPClient
func (_mock *MockIMAPClient) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMAPClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockIMAPClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockIMAPClient_Expecter) Stop() *MockIMAPClient_Stop_Call {
	return &MockIMAPClient_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockIMAPClient_Stop_Call) Run(run func()) *MockIMAPClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMAPClient_Stop_Call) Return(err error) *MockIMAPClient_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMAPClient_Stop_Call) RunAndReturn(run func() error) *MockIMAPClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}
