// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
)

// NewMockCoreStorageProtocolComposite creates a new instance of MockCoreStorageProtocolComposite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoreStorageProtocolComposite(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoreStorageProtocolComposite {
	mock := &MockCoreStorageProtocolComposite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoreStorageProtocolComposite is an autogenerated mock type for the CoreStorageProtocolComposite type
type MockCoreStorageProtocolComposite struct {
	mock.Mock
}

type MockCoreStorageProtocolComposite_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoreStorageProtocolComposite) EXPECT() *MockCoreStorageProtocolComposite_Expecter {
	return &MockCoreStorageProtocolComposite_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) Config() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockCoreStorageProtocolComposite_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockCoreStorageProtocolComposite_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockCoreStorageProtocolComposite_Expecter) Config() *MockCoreStorageProtocolComposite_Config_Call {
	return &MockCoreStorageProtocolComposite_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockCoreStorageProtocolComposite_Config_Call) Run(run func()) *MockCoreStorageProtocolComposite_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Config_Call) Return(protocolConfig config.ProtocolConfig) *MockCoreStorageProtocolComposite_Config_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Config_Call) RunAndReturn(run func() config.ProtocolConfig) *MockCoreStorageProtocolComposite_Config_Call {
	_c.Call.Return(run)
	return _c
}

// EncodeFileName provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) EncodeFileName(storageHash core.StorageHash) string {
	ret := _mock.Called(storageHash)

	if len(ret) == 0 {
		panic("no return value specified for EncodeFileName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) string); ok {
		r0 = returnFunc(storageHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCoreStorageProtocolComposite_EncodeFileName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeFileName'
type MockCoreStorageProtocolComposite_EncodeFileName_Call struct {
	*mock.Call
}

// EncodeFileName is a helper method to define mock.On call
//   - storageHash core.StorageHash
func (_e *MockCoreStorageProtocolComposite_Expecter) EncodeFileName(storageHash interface{}) *MockCoreStorageProtocolComposite_EncodeFileName_Call {
	return &MockCoreStorageProtocolComposite_EncodeFileName_Call{Call: _e.mock.On("EncodeFileName", storageHash)}
}

func (_c *MockCoreStorageProtocolComposite_EncodeFileName_Call) Run(run func(storageHash core.StorageHash)) *MockCoreStorageProtocolComposite_EncodeFileName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_EncodeFileName_Call) Return(s string) *MockCoreStorageProtocolComposite_EncodeFileName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_EncodeFileName_Call) RunAndReturn(run func(storageHash core.StorageHash) string) *MockCoreStorageProtocolComposite_EncodeFileName_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) Hash(r io.Reader, size uint64) (core.StorageHash, error) {
	ret := _mock.Called(r, size)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 core.StorageHash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader, uint64) (core.StorageHash, error)); ok {
		return returnFunc(r, size)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader, uint64) core.StorageHash); ok {
		r0 = returnFunc(r, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.StorageHash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader, uint64) error); ok {
		r1 = returnFunc(r, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCoreStorageProtocolComposite_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockCoreStorageProtocolComposite_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - r io.Reader
//   - size uint64
func (_e *MockCoreStorageProtocolComposite_Expecter) Hash(r interface{}, size interface{}) *MockCoreStorageProtocolComposite_Hash_Call {
	return &MockCoreStorageProtocolComposite_Hash_Call{Call: _e.mock.On("Hash", r, size)}
}

func (_c *MockCoreStorageProtocolComposite_Hash_Call) Run(run func(r io.Reader, size uint64)) *MockCoreStorageProtocolComposite_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Hash_Call) Return(storageHash core.StorageHash, err error) *MockCoreStorageProtocolComposite_Hash_Call {
	_c.Call.Return(storageHash, err)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Hash_Call) RunAndReturn(run func(r io.Reader, size uint64) (core.StorageHash, error)) *MockCoreStorageProtocolComposite_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCoreStorageProtocolComposite_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCoreStorageProtocolComposite_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCoreStorageProtocolComposite_Expecter) Name() *MockCoreStorageProtocolComposite_Name_Call {
	return &MockCoreStorageProtocolComposite_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCoreStorageProtocolComposite_Name_Call) Run(run func()) *MockCoreStorageProtocolComposite_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Name_Call) Return(s string) *MockCoreStorageProtocolComposite_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Name_Call) RunAndReturn(run func() string) *MockCoreStorageProtocolComposite_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockCoreStorageProtocolComposite_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockCoreStorageProtocolComposite_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockCoreStorageProtocolComposite_Expecter) Operations() *MockCoreStorageProtocolComposite_Operations_Call {
	return &MockCoreStorageProtocolComposite_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockCoreStorageProtocolComposite_Operations_Call) Run(run func()) *MockCoreStorageProtocolComposite_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Operations_Call) Return(operations []core.Operation) *MockCoreStorageProtocolComposite_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Operations_Call) RunAndReturn(run func() []core.Operation) *MockCoreStorageProtocolComposite_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// Workflows provides a mock function for the type MockCoreStorageProtocolComposite
func (_mock *MockCoreStorageProtocolComposite) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockCoreStorageProtocolComposite_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockCoreStorageProtocolComposite_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockCoreStorageProtocolComposite_Expecter) Workflows() *MockCoreStorageProtocolComposite_Workflows_Call {
	return &MockCoreStorageProtocolComposite_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockCoreStorageProtocolComposite_Workflows_Call) Run(run func()) *MockCoreStorageProtocolComposite_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockCoreStorageProtocolComposite_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockCoreStorageProtocolComposite_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockCoreStorageProtocolComposite_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
