// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/baruwa-enterprise/clamd"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScannerClient creates a new instance of MockScannerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScannerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScannerClient {
	mock := &MockScannerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScannerClient is an autogenerated mock type for the ScannerClient type
type MockScannerClient struct {
	mock.Mock
}

type MockScannerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScannerClient) EXPECT() *MockScannerClient_Expecter {
	return &MockScannerClient_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockScannerClient
func (_mock *MockScannerClient) Ping(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScannerClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockScannerClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScannerClient_Expecter) Ping(ctx interface{}) *MockScannerClient_Ping_Call {
	return &MockScannerClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockScannerClient_Ping_Call) Run(run func(ctx context.Context)) *MockScannerClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScannerClient_Ping_Call) Return(b bool, err error) *MockScannerClient_Ping_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockScannerClient_Ping_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockScannerClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ScanReader provides a mock function for the type MockScannerClient
func (_mock *MockScannerClient) ScanReader(ctx context.Context, r io.Reader) ([]*clamd.Response, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for ScanReader")
	}

	var r0 []*clamd.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) ([]*clamd.Response, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) []*clamd.Response); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*clamd.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScannerClient_ScanReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanReader'
type MockScannerClient_ScanReader_Call struct {
	*mock.Call
}

// ScanReader is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
func (_e *MockScannerClient_Expecter) ScanReader(ctx interface{}, r interface{}) *MockScannerClient_ScanReader_Call {
	return &MockScannerClient_ScanReader_Call{Call: _e.mock.On("ScanReader", ctx, r)}
}

func (_c *MockScannerClient_ScanReader_Call) Run(run func(ctx context.Context, r io.Reader)) *MockScannerClient_ScanReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScannerClient_ScanReader_Call) Return(responses []*clamd.Response, err error) *MockScannerClient_ScanReader_Call {
	_c.Call.Return(responses, err)
	return _c
}

func (_c *MockScannerClient_ScanReader_Call) RunAndReturn(run func(ctx context.Context, r io.Reader) ([]*clamd.Response, error)) *MockScannerClient_ScanReader_Call {
	_c.Call.Return(run)
	return _c
}
